### ISSUE TITLE
[BUG] getListing: incorrect original_creation_timestamp

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#108]
**Describe the bug**
We are trying to accurately determine when a listing is first published. 

We have tried using `original_creation_timestamp` but that shows when the draft was created, and that can vary greatly from when the seller finally publishes a listing.

`creation_timestamp` was also tested, which at first glance seemed more accurate. However,  `creation_timestamp` changes as the listing gets renewed and we can no longer determine the date the listing was first published.

**To Reproduce**
Check API response for any listing that has been renewed.

**Expected behavior**
Show the original publish date in the `original_creation_timestamp` or add new response like `original_publish_timestamp`.

**Comment by benjymouse** [comment]
Checking in to see if any updates on this one? Thanks

**Comment by harjas** [comment]
Hey @benjymouse! This would require updates to the listing model which can affect things across the etsy ecosystem. This is not something that's on our radar to address as of yet. 

Since you labeled this as a bug, do you see the behavior for original_creation_timestamp in v3 to be different than v2? If v2 and v3 are already in line then there's little we can do here. If v2's behavior worked for you but v3 doesn't (ie, you see the response values for the same field between v3 and v2 to be different), that's something we can look into.

**Comment by benjymouse** [comment]
Got it thanks @harjas. I believe v3 is consistent with v2. I think this can be closed but would be great if it could be looked into for future updates.
