### ISSUE TITLE
[ENDPOINT] Proposed design change for /v3/application/shops/{shop_id}/receipts/{receipt_id}/transactions

### ISSUE THREAD

**Issue by SEPAHL** [etsy/open-api#111]
**Current Endpoint Design**
Current design does not include the item SKU nor the variations nor the personalisation added by the customer during checkout

**Proposed Endpoint Design Change**
Please add the SKU, variations and personalisation

**Why are you proposing this change?**
SKU/variations: required to identify the right item
personalisation: To process the customer wish within our system

**Comment by Gareth064** [comment]
Variations and Personalization needs to be in the API, as they are in V2, otherwise my app becomes useless.

**Comment by WheelerCC** [comment]
Just gonna add that I strongly agree. Adding functionality would also decrease the number of API calls needing to be made for many use cases, as a reasonable number of users will track products between platforms via SKUs. With the current set of endpoints, we'd need to get a list of transactions and then for each unique listing/product ID call getListingProduct to retrieve its SKU. Given there are so few fields returned from getListingProduct, could its results not just be included in the results of anything which returns a transaction? e.g. both getShopReceiptTransactionsByReceipt and getShopReceiptTransactionsByShop.

Similarly, there is some overlap between information provided by any endpoints that return either a list of receipts or transactions, with important things being omitted from both (meaning you need to call both of them..!). e.g. say you want to retrieve the shipping address for the latest 10 receipts in your shop, and the SKU of the listingProducts that needed to be included in the package sent to them. You need to call 3 endpoints to get enough information to do all of this...

**Comment by stickfigure** [comment]
In addition to echoing the need for the SKU in the transaction/receipt, I want to ask a question:

What happens if the user edits the listing and deletes the product. Do existing transactions now have dangling pointers to products we can no longer fetch?

**Comment by etsyachristensen** [comment]
The shipping data is nearly ready to start showing up in the receipt. Hopefully by the end of the week.

The SKU we are working on still adding to the receipt and other listing endpoints. It's a bit complicated.

@stickfigure to answer your question about the product, no we don't delete the products from the system for that very reason. We have to have the history available. When inventory is updated, new product ids are generated so that we can maintain the history. If a product is removed, the data for that product is still retrievable on the various api calls that need that data.

**Comment by etsyachristensen** [comment]
This is done. We pushed this out last week I believe. Sorry for not replying back. Been a busy time.

When you call the `getShopReceiptTransactionsByShop` or `getShopReceiptTransaction` endpoint you will get the `variations` array in the transaction object. Since the receipt endpoints now also include the transactions, this information will show up in those endpoints as well. For example:
![image](https://user-images.githubusercontent.com/83842847/134531157-5892b811-b969-48c2-b52c-611e0c5929d5.png)

I'm still working on adding the SKU to the transaction endpoints but it's complicated by the fact that a sku could be tied to a variation and not just a listing.

**Comment by mordyort** [comment]
I don't look at the receipt im calling https://api.etsy.com/v3/application/shops/shopid/transactions and i don't see the SKU but documentation says the SKU should show there please advise if this will be added to the get transactions so i wont need to make a separate call and if the SKU of a variation will be displayed
