### ISSUE TITLE
[BUG] unable to set item weight

### ISSUE THREAD

**Issue by tlesiuk** [etsy/open-api#125]
I found that it's unable to set item weight, described here https://help.etsy.com/hc/en-us/articles/115013946647-How-to-Set-Up-Calculated-Shipping-?segment=selling#h_83b0916b-7541-4bb9-845a-6bef2f9f8c17
Also, please note that item weight and item weight unit are present in Listing https://www.etsy.com/developers/documentation/reference/listing

**Comment by etsyachristensen** [comment]
@tlesiuk This should be fixed now. Just be sure to also include the `item_weight_unit` variable with the unit value.

**Comment by tlesiuk** [comment]
@etsyachristensen Sorry, I think that you don't understand me correctly. I mean, that I can't set item weight on UI in listing.

**Comment by etsyachristensen** [comment]
@tlesiuk Thanks for clarifying. Since this isn't an API specific issue, but rather a UI related issue, I need to ask you to contact Etsy via the contact page here: https://www.etsy.com/help/contact

This will ensure that the right team member picks up the issue and helps resolve it as quickly as possible.
