### ISSUE TITLE
[FEATURE] Transaction need variations field

### ISSUE THREAD

**Issue by duylddev** [etsy/open-api#138]
In API v2, we have `variations` field in` LIST Transaction` request like "White-S" for T-Shirt
But I didn't find this on API v3. We need this

**Comment by joaquin102** [comment]
This is crucial for most of the user of the Api. This is already in the V2.

**Comment by Gareth064** [comment]
Agreed. There are now 4 separate issues about this Etsy guys. Can we get some acknowledgement please.
#101 
#111 
#142

**Comment by etsyachristensen** [comment]
Not to worry everyone. It's high on our list of priorities! Will keep you all updated.

**Comment by Gareth064** [comment]
Thank you. I can start to relax now.... Well I still have the stress of porting my app but one step at a time 😂

**Comment by vitahlin** [comment]
How is the progress of this issue?

**Comment by etsyachristensen** [comment]
This is done @vitahlin. We pushed this out last week I believe. When you call the `getShopReceiptTransactionsByShop` or `getShopReceiptTransaction` endpoint you will get the `variations` array in the transaction object. Since the receipt endpoints now also include the transactions, this information will show up in those endpoints as well. For example:
![image](https://user-images.githubusercontent.com/83842847/134531157-5892b811-b969-48c2-b52c-611e0c5929d5.png)
