### ISSUE TITLE
[BUG] getListingInventory does not provide deleted products

### ISSUE THREAD

**Issue by ww2406** [etsy/open-api#226]
**Describe the bug**
getListingInventory only provides non-deleted products. But, this is not documented and there doesn't seem to be another way (unless I've missed it) to get deleted products.

**To Reproduce**
Submit a request to getListingInventory on a listing with a deleted product entry. Only the currently active product(s) return.

**Expected behavior**
I would expect both non-deleted and deleted products to return, given that it isn't documented otherwise and there's a is_deleted field present.

**Additional context**
I'm not sure if this is an actual bug where you all intended it to return all products and it's not, or an opportunity to clarify documentation and a feature request. In either case, while I imagine returning only active products is by far the more common use case, someway to get deleted products (new endpoint, adding a state parameter like in getListingsByShop, or something else) is necessary for some uses.

**Comment by etsyachristensen** [comment]
@ww2406 It's not technically a bug, but I can certainly understand the confusion. There's a lot of technical stuff surrounding inventory. I'll look into the system and see what I can find.

**Comment by etsyachristensen** [comment]
@ww2406 We added a new input for the getListingInventory endpoint called `show_deleted` that's a boolean. This will return the deleted variations in inventory along with their offerings and property values.

Please bear in mind, that if you use this call with the show_deleted to get the current inventory in order to update the inventory you need to remember to remove the deleted items from the data set before re-posting back to the updateListingInventory endpoint.
