### ISSUE TITLE
The update_timestamp does not change when expected_ship_date is modified

### ISSUE THREAD

**Issue by chris-rogala** [etsy/open-api#232]
**Describe the bug**
When the ship by date is changed on an order, the `update_timestamp` does not change. 

**To Reproduce**

Send the below cURL:

```
curl --location --request GET 'https://openapi.etsy.com/v3/application/shops/7974117/receipts/2180773521' \
--header 'x-api-key: {{apiKey}}' \
--header 'Authorization: Bearer {{accessToken}}'
```

The update_timestamp is 1631672394 (Wed Sep 15 2021 02:19:54 GMT+0000). The ship by date was modified on 9/17/2021:

![image](https://user-images.githubusercontent.com/44238629/134052817-66e51919-ee7e-4e84-adba-a3fbc4719609.png)

**Expected behavior**
The update_timestamp should change when the expected_ship_date is modified.

**Screenshots**
See above

**Additional context**
Initially mentioned here: https://github.com/etsy/open-api/issues/211#issuecomment-922122192

**Comment by etsyachristensen** [comment]
@chris-rogala I had a chat with our internal staff here regarding updating that field. Unfortunately there's nothing we can do about changing that field. In his words:
> Receipts and transactions are supposed to be static, since they are recording financial information and are point-of-checkout data. I dont have opinions on how the API works, but its intentional that we dont change that date on the actual receipt record because we never update the row in the database

With that said, I will close this issue out for now. Maybe we can find a way in the future to provide a most recent change date.

**Comment by chris-rogala** [comment]
@etsyachristensen I understand that date must stay static on a receipt, but we are changing the ship by date which is a change on the receipt. If I print the receipt in Etsy, the ship by date does not reflect the original date. I don't think closing this is the correct solution. I think relabeling this is more appropriate. Additionally, the `max_last_modified` query parameter is not accurate. The [definition](https://developers.etsy.com/documentation/reference#operation/getShopReceipts) is:

`The latest unix timestamp for when a record last changed.`

The record was changed and therefor, the receipt should be returned. Irrelevant of the financial reasoning behind the property mentioned, the record in the API was changed. What I mean by that is that if I hashed the result and then changed the ship by date, the hash would be different the next time I pulled the receipt. The same can be said when the receipt is shipped.

Please consider reopening this and adding it to the backlog instead of sweeping it under the rug. Thanks!

**Comment by Gareth064** [comment]
@etsyachristensen I agree completely with @chris-rogala here. I don't see how the internal staff say that the "Receipt" and its associated "Transactions" are meant to be static when there are details within it which can change. **Status**, **Is_Paid**, **Is_Shipped** are 3 things on the Receipt which can be changed and will result in the **update_timestamp** to change.

Allowing you to change the **Expected Dispatch Date** via the GUI, must result in the **expected_ship_date** to change on the Transaction/s otherwise how is it persisted to be displayed back on the GUI again? 

Digging into the data returned from your internal APIs (using browser dev tools), the **expected_ship_date** isn't on the "transaction" object against an order/receipt. Its nested inside a "fulfillment" object inside the order/receipt
![image](https://user-images.githubusercontent.com/22307223/147893400-9b320c8e-f18e-4069-8bfc-f6cf25aa4da2.png)
This makes a lot more sense because on the GUI you can only have an **Expected Dispatch Date** for the whole order/receipt, not per item/transaction. So with the Open API, having the **expected_ship_date** be on the **transaction** doesn't make sense since transaction data is meant to be static and doesn't have an **update_timestamp** property against it, just a **create_timestamp**.

So something isn't right somewhere.

Either the structure of the Receipt and Transaction data isn't correct in the Open API.

**OR** the structure is correct and transaction data (specficially expected_ship_date) **is** updated, but you currently aren't providing the Open API a way of discovering that it's changed by providing both a **update_timestamp** AND an endpoint to query transactions on their own like **GetTransactions** with filters for **max/min_last_modified**.

Another possibility is that the transaction data is static but there is a related table somewhere in your db which holds a history of the **expected_ship_date** to show that it has changed/is different from what's on the transaction and your internal API uses that related table to get the latest Expected Disptach Date to display on the GUI.

Sorry, I am quite passionate about this subject also 😜. This xmas past we had to push a quite a few Dispatch dates out and not being able to reflect that in the App I built, for managing our orders, was annoying and resulted in having to remember to put a note (in my app) on the order to remind us that the dispatch date has change which is just results in human error when you are super busy 😂

**Comment by etsyachristensen** [comment]
@chris-rogala @Gareth064 We have made the change to the receipt endpoints to ensure that the updated_timestamp is returned with the latest activity on the receipt (refund/transaction etc). See https://github.com/etsy/open-api/releases/tag/3.0.0-general-release-2022-07-19
