### ISSUE TITLE
[BUG] createDraftListing tags

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#291]
**Describe the bug**
According to documentation, when creating a draft listing, tags field should be an array of string, meaning ['tag1', 'tag2']
Using this input creates only one tag with the last value from the array (tag2)
If I send a string with comma separated values ("tag1,tag2") 2 tags will be created

**To Reproduce**
Invoke createDraftListing with an array of string at tags field

**Expected behavior**
Listing will be created with tags according to the array

**Screenshots**

**Additional context**

**Comment by assaflei** [comment]
Any updates on this?

**Comment by etsyachristensen** [comment]
@assaflei We reviewed this ticket and realized the documentation is confusing. The way the documentation is generated makes it look like it's supposed to be an array of strings. But this is because the input accepts a string, then converts to an array, but may be null. So the line above the description for this says "Array of strings Nullable".

We're updating the description to specify that it's a comma delimited list of strings. Hopefully that helps clarify things.
