### ISSUE TITLE
[BUG] - Variation with property_id 200 and value_id xxx is invalid

### ISSUE THREAD

**Issue by carlosmartinez-dev** [etsy/open-api#300]
**Describe the bug**
When I am attempting to invoke the V3 API 

  `https://openapi.etsy.com/v3/application/shops/<shop_id>/listings/<listing_id>/variation-images`, 

I am getting following error:

  `Could not update variation images because of the following error: variation with property_id 200 and value_id 49928889190 is invalid
`

The endpoint I am using to get the value_id is also from V3:

  `https://openapi.etsy.com/v3/application/shops/<channel_shop_id/listings/<listing_id>
`

This issue seems to be already reported [here](https://issueexplorer.com/issue/etsy/open-api/148) but I did not find it here in etsy/open-api.

**Additional context**

```
{
    "message": "Bad Request",
    "status": 400,
    "text": "{\"error\":\"Could not update variation images because of the following error: variation with property_id 200 and value_id 49928889190 is invalid\"}\n",
    "method": "POST",
    "path": "/v3/application/shops/30715180/listings/1118340250/variation-images",
    "url": "https://openapi.etsy.com/v3/application/shops/30715180/listings/1118340250/variation-images",
    "params": {
        "variation_images": [
            {
                "value_id": 49928889190,
                "property_id": 200,
                "image_id": 3507876610
            },
            {
                "value_id": 52041479579,
                "property_id": 200,
                "image_id": 3555507685
            },
            {
                "value_id": 49928889192,
                "property_id": 200,
                "image_id": 3507876610
            }
        ]
    }
}
```

**Comment by etsyachristensen** [comment]
@carlosmartinez-dev I deployed a change today that might help fix this issue. Can you try it again and let me know?

**Comment by carlosmartinez-dev** [comment]
Thanks @etsyachristensen , let me retry and let you know

**Comment by carlosmartinez-dev** [comment]
@etsyachristensen same issue, I tried updating the images for the variations and actually I am getting same value_ids:

{
    "message": "Bad Request",
    "status": 400,
    "text": "{\"error\":\"Could not update variation images because of the following error: variation with property_id 200 and value_id 49928889190 is invalid\"}\n",
    "method": "POST",
    "path": "/v3/application/shops/30715180/listings/1137960205/variation-images",
    "url": "https://openapi.etsy.com/v3/application/shops/30715180/listings/1137960205/variation-images",
    "params": {
        "variation_images": [
            {
                "value_id": 49928889190,
                "property_id": 200,
                "image_id": 3554300469
            },
            {
                "value_id": 49928889192,
                "property_id": 200,
                "image_id": 3555507685
            },
            {
                "value_id": 52041479579,
                "property_id": 200,
                "image_id": 3508915006
            }
        ]
    }
}

**Comment by carlosmartinez-dev** [comment]
Hi @etsyachristensen, happy new year 😄, any news on this one?

**Comment by neekfenwick** [comment]
I think I'm getting this also, today with a freshly created draft listing, I think it's because I don't understand how to get value_id values for my custom colours. I find the tutorial at https://developers.etsy.com/documentation/tutorials/listings does not explain how to create value_id values for custom property values.  @carlosmartinez-dev  maybe this is similar to your situation?

I tried to create a draft listing with custom colours, so I set up the 'products' array with `property_values` with my colours, but I did not know what to use for the `value_ids`, so I just made them up, e.g.:

```
property_values: [
  [ property_id: 200,
  property_name: 'Primary color',
  scale_id: null,
  scale_name: null,
  value_ids: [ 55998730829 ] // This is totally bogus
  values: [ 'Anthracite Grey' ] // our custom colour name
  ]
]
```

When I later try to associate images to these variations, because the value_ids I used for the property_values in the listing were made up, I got a `variation with property_id 200 and value_id 1 is invalid` error.  (the first is actually Black i.e. value_id 1, but because I had set the property_values entry for "Black" to my hardcoded value_id 55998730829, the value_id 1 doesn't exist on my listing, hence the error).

If, instead, I create the listing using only "official" colour properties, it works OK.  e.g. I got the colour value_id values by calling `application/seller-taxonomy/nodes/989/properties` and iterating the values for property_id 200 ("Primary color") so I'm sure they are correct.  e.g. value_id 1 is "Black".  So right now I am mapping all my custom colour to only those found in the "Primary colors" list, but we really don't want to do this because our custom colour names are very popular and good for SEO.

How did you get your value_id values like 49928889190?  Are these custom colour names that you want to use, like me, that don't exist in the "Primary color" list in the taxonomy data?

**Comment by carlosmartinez-dev** [comment]
Hi @neekfenwick , sorry for the late reply.
I get the value_id like 49928889190 by first making a call to this api https://www.etsy.com/developers/documentation/reference/listing and including `Variations` in the parameters (this is an association described here https://www.etsy.com/developers/documentation/reference/listing#section_associations), the response contains the value_id that I am suppose to use to later make the update but it is failing. Note that this only happens for variations which Property id = 200 (Primary color).

Another way to get the value_id that I have not tried yet is with this API: https://www.etsy.com/developers/documentation/reference/listingvariationimage

**Comment by yovasx2** [comment]
V2 also failing:


2022-03-17T20:40:21.780Z ==> error: Upload failed for product 7303685 - applyOps shopId 25190 userDb db5. Error: Error: {"message":"Bad Request","status":400,"text":"variation with property_id 200 and value_id 51995096597 is invalid","method":"POST","path":"/v2/listings/1195609441/variation-images","url":"https://openapi.etsy.com/v2/listings/1195609441/variation-images","params":{"variation_images":[{"value_id":51995096597,"property_id":200,"image_id":3742704174},{"value_id":51985709075,"property_id":200,"image_id":3790294095}]}}. Stack: Error: {"message":"Bad Request","status":400,"text":"variation with property_id 200 and value_id 51995096597 is invalid","method":"POST","path":"/v2/listings/1195609441/variation-images","url":"https://openapi.etsy.com/v2/listings/1195609441/variation-images","params":{"variation_images":[{"value_id":51995096597,"property_id":200,"image_id":3742704174},{"value_id":51985709075,"property_id":200,"image_id":3790294095}]}}

**Comment by yovasx2** [comment]
we detected a similar error for another property id 513
```
2022-05-11T19:32:02.054Z ==> error: error handled: Error: {"message":"cannot POST /v3/application/shops/20394897/listings/855095251/variation-images (400)","status":400,"text":"{\"error\":\"Could not update variation images because of the following error: variation with property_id 513 and value_id 55180423543 is invalid\"}\n","method":"POST","path":"/v3/application/shops/20394897/listings/855095251/variation-images","url":"https://openapi.etsy.com/v3/application/shops/20394897/listings/855095251/variation-images","params":{"variation_images":[{"value_id":55180423543,"property_id":513,"image_id":2469059494}]}}. Custom message: Product ID 9321162, correlationId: 68b052a1-6fcb-4317-a5b6-940f8b62ab4e, shopId: 12093, userDb: db4
```

**Comment by etsyachristensen** [comment]
@yovasx2 I just checked and that value_id belongs to property id 514, not 513:
![image](https://user-images.githubusercontent.com/83842847/167944145-eff9dbc0-6a2f-4db9-a262-c3b59df1aa9b.png)

**Comment by yovasx2** [comment]
we obtained the ids from the properties endpoint is that wrong?

**Comment by etsyachristensen** [comment]
No that is how it should be done, but is that endpoint showing you that value id being tied to property 513? It shouldn't be.
