### ISSUE TITLE
Add data around refunds to ledger and receipt objects

### ISSUE THREAD

**Issue by zoborg** [etsy/open-api#302]
**Current Endpoint Design**

@etsyachristensen 

The current API retrieves payments that were associated with a ledger, however when a refund occurs there is no way to either retrieve the original Payment (and therefore receipt) nor what formed the refund.  On the V2 API the findPaymentAdjustmentForPaymentAccountLedgerEntry would allow us to retrieve the adjustment, then use the findPayment to lookup the original order and associated data.

**Proposed Endpoint Design Change**

Either adapt the API so REFUND ledger entries work in the same way as PAYMENTS, or create a new endpoint that allows the developer to query the refunds so that it can be determined what was actually refunded in the same way the V2 API worked

**Why are you proposing this change?**

Refunds form an important part of the order lifecycle, in our particular use case, the refund is needed so that the seller can accurately report their tax information to the relevant tax authority.  Tax (or specifically VAT) is determined by a number of points, a simple case is that if a seller based in the UK sold an item to the US, then that sale would not be subject to VAT (whilst a sale to the UK would).  At the moment the destination country can be found when looking up the payment/receipt and therefore the correct tax be paid.  However as there is no support for looking up refunds, when a refund happens the seller (without manually checking each refund in their shop) would not be able to correctly determine if the VAT was applicable (and therefore refundable) or not.

**Comment by shoecake** [comment]
I also ran into this issue recently for exactly the same reason! 

I have used the V2 API findPaymentAdjustmentForPaymentAccountLedgerEntry to get the payment adjustment record - this has the refund details on (total amount refunded to customer and fee refund to seller) in addition to the receipt_id

Access to the payment adjustment record is preferable in this case as a partial or multiple refunds may have occurred to an order.

This endpoint needs to be re-created in V3

**Comment by evangelosdaniil** [comment]
We are also facing this issue for the same reasons mentioned above.

Another proposed solution would be to include the `payment_id` on the Refund Ledger Entry to get the Payment using the Ledger Entry Payment endpoint.

**Comment by shoecake** [comment]
I would not support providing the payment_id instead of the payment_adjustment_id on the ledger entry as the ledger entry relates to a specific adjustment, not a payment. 

It is conceivable that multiple refunds may be made against a payment (so multiple results in the payment_adjustments collection of the payment object).  Providing the payment_id would not be specific enough to be able to determine the specific payment adjustment the ledger entry relates to.

**Comment by linkmybooks** [comment]
@etsyachristensen - any chance this could be looked at please? it's another blocker from fully migrating to the V3 API?

**Comment by zoborg** [comment]
@etsyachristensen - any chance this could be looked at please? it's another blocker from fully migrating to the V3 API?

**Comment by zoborg** [comment]
> I would not support providing the payment_id instead of the payment_adjustment_id on the ledger entry as the ledger entry relates to a specific adjustment, not a payment.
> 
> It is conceivable that multiple partial refunds may be made against a payment (so multiple results in the payment_adjustments collection of the payment object). Providing the payment_id would not be specific enough to be able to determine the specific payment adjustment the ledger entry relates to.

@shoecake - yes I agree, the V2 API had findPaymentAdjustmentForPaymentAccountLedgerEntry which you could then use the findPayment to retrieve the original.. PaymentAdjustments don't appear on this API at all (gulp)

**Comment by samborambo305** [comment]
@etsyachristensen is there any update on this on Etsy's end?

**Comment by evangelosdaniil** [comment]
@etsyachristensen any update from your side?

**Comment by etsyachristensen** [comment]
Sorry for the delay.

Are you unable to find the payment adjustments in the `getPayments` endpoint? https://developers.etsy.com/documentation/reference/#operation/getPayments

Or in the `getPaymentAccountLedgerEntryPayments`
https://developers.etsy.com/documentation/reference/#operation/getPaymentAccountLedgerEntryPayments

I may be confused as to the issue here.

**Comment by multiorders** [comment]
Hi @etsyachristensen we have investigated the getPayments endpoint and you are correct, but to get information from it we first need to get the payment_id's, which from what I understand can only be done via getShopPaymentByReceiptId?
it does return all relevant payment and refund info, but there are two problems we are facing with the current solution:

1. There is no way of getting Payment info for a group of orders (receipts) in one go. We need to get the each individual orders payment info separately so it further strains the request limits. Do you think it would be possible to reveal payment_id within the main "https://openapi.etsy.com/v3/application/shops/{{Shop Id}}/receipts request?" We could then do bulk checks for relevant data?

2. Once an order is marked as Canceled it's payment info can no longer be requested using the getShopPaymentByReceiptId method. Why? It feels like if we had Cancelation info within there as a "reason_code": we wouldn't need to do additional per order checks to see if anything is canceled.

**Comment by sergey-chegaev** [comment]
@etsyachristensen
We need a mechanism to get `PaymentAdjustment`'s related `Payment`, having only `LedgerEntry` associated with the `PaymentAdjustment`.
This `LedgerEntry` is one related to `Payment`:
```
{
  "entry_id": 11377948894,
  "ledger_id": 8080291933,
  "sequence_number": 42,
  "amount": 104,
  "currency": "EUR",
  "description": "PAYMENT_GROSS",
  "balance": 52,
  "create_date": 1641460767,
  "ledger_type": "PAYMENT_GROSS",
  "reference_type": "shop_payment",
  "reference_id": 101096642631
}
```
We can fetch an actual `Payment` with a new V3 API endpoint [getPaymentAccountLedgerEntryPayments](https://developers.etsy.com/documentation/reference/#operation/getPaymentAccountLedgerEntryPayments), and then fetch a related `Receipt` and all other needed entities to get all transaction details.

But `LedgerEntry` for refund looks like this:
```
{
  "entry_id": 11594841764,
  "ledger_id": 8080291933,
  "sequence_number": 49,
  "amount": -104,
  "currency": "EUR",
  "description": "REFUND_GROSS",
  "balance": -122,
  "create_date": 1643279015,
  "ledger_type": "REFUND_GROSS",
  "reference_type": "payment_adjustment",
  "reference_id": 100307830422
}
```
There is a stored reference to `payment_adjustment` entity. Using V2 API we were able to fetch `PaymentAdjustment` via [findPaymentAdjustmentForLedgerEntry](https://www.etsy.com/developers/documentation/reference/paymentadjustment#method_findpaymentadjustmentforledgerentry). Then we could fetch related `AdjustmentItem`s (for tracking returned withheld taxes), `Payment` and all other needed entities to get full-details of refunded transaction.

In the new V3 API there are no separate endpoints for `Adjustment` and `AdjustmentItem` entities, hence we cannot fetch them directly having only `LedgerEntry` associated with the `PaymentAdjsutment`.

Also, there is no link for related `Payment` (or any other linking entity) in the `LedgerEntry` associated with a refund and we cannot understand what payment was actually refunded. The [V3 getPaymentAccountLedgerEntryPayments](https://developers.etsy.com/documentation/reference/#operation/getPaymentAccountLedgerEntryPayments) doesn’t return payment if we provide the id of the `LedgerEntry` associated with a refund.

**Summary**
Using V3 API, we cannot get any of the refund details - only basic info in Ledger’s currency.
Since we providing an accounting solution, this information is very critical for us and it's absence is preventing us from migration to the new V3 API.

**Comment by etsyachristensen** [comment]
@sergey-chegaev @multiorders @evangelosdaniil @samborambo305 @zoborg @shoecake @andriuspuskorius 
This has been shortlisted for development. We haven't begun the work just yet, but the running thought is to include the refund information as part of the receipt and ledger endpoints, rather than create new endpoints to be queried for the payment adjustments. We will of course let you know when this is completed.

**Comment by etsyachristensen** [comment]
Would any of you be able to provide me with a shop id and a few receipt ids that should have refunds on them? This will help me test the work I'm doing to ensure that what we are providing is what you actually need. These ids themselves aren't generally a secure value so you can share them here, or you can email developers@etsy.com and mention this issue number and request that it be forwarded to me (Andrew Christensen) so I can use that info.

For the `Shop Receipt` endpoints, I'm planning to add the refunds in as an array of data. It won't be a lot of data, but enough to see when a receipt has a refund attached and how much it was for.

For the `Payment` endpoints (`getPayments`, `getShopPaymentByReceiptId` and `getPaymentAccountLedgerEntryPayments`) endpoints, what all is needed to make this usable for you? Is it a matter of adding the adjustment items to the payment_adjustments array?

For the `LedgerEntry` endpoint if you see something like this:
```
  "ledger_type": "REFUND_GROSS",
  "reference_type": "payment_adjustment",
  "reference_id": 100307830422
```
The reference_id is the payment_adjustment_id. This should correspond to the payment_adjustment_id in the payment_adjustments array in the `Payment` endpoints. The reason we don't call it a `payment_adjustment_id` but instead a `reference_id` is because the adjustment may be a reference to any number of other actions. So reference_id is the id of the corresponding action.

**Comment by GiorgosPanagiotopoulos** [comment]
Hello @etsyachristensen,

Thank you for the response and the explanation. I understand that a refund breakdown will be possible by using the "reference_id" to find the corresponding information in the relative payment and receipt. 

But how will we identify this payment and receipt having only the `LedgerEntry` of the refund? As @sergey-chegaev mentioned, in V2 we were able to use [findPaymentAdjustmentForLedgerEntry](https://www.etsy.com/developers/documentation/reference/paymentadjustment#method_findpaymentadjustmentforledgerentry) in order to get the refund information and with the `payment_id` contained in the response we could link the corresponding payment with this refund. Will we be able to use the refund's "reference_id" in any of the `Payments` endpoints?

**Comment by sergey-chegaev** [comment]
@etsyachristensen
**Shop Id**: 27673215
**Ledger Entry Id for Payment**: 11594841764
**Payment id**: 101096642631
**Receipt id**: 2335394517
**Ledger Entry Id for Payment Adjustment (Refund)**: 11594841764
**Payment Adjsutment Id (Refund)**: 100307830422

**Comment by etsyachristensen** [comment]
Thanks @sergey-chegaev! That should help a lot. I'll let you know if i had anymore questions or progress.

**Comment by etsyachristensen** [comment]
@sergey-chegaev So here's what I've been working on and using your example above, here's a modified output of the `getShopPaymentAccountLedgerEntries` showing two entries that contain adjustments as well as the adjustment items as part of the data array.
https://gist.github.com/etsyachristensen/7f5c2e2b809b6693c9b9b86124132f8f (Once you've reviewed this, I'll delete the gist.)

Will a change like this work for your needs? I am also working to add refund data to the receipts as well, though I'm not sure if this helps you.

Please review at your earliest convenience and let me know if this is what you're looking for. I'm not a financials guy so I'm not sure I follow all the terminology of your needs. The main thing I'm trying to avoid is creating new endpoints, especially those that were listed as retired.

**Comment by sergey-chegaev** [comment]
@etsyachristensen Basically, attaching a payment adjustment to the `LedgerEntry` will work for us since it gives us ability to get information from related `PaymentAdjsutment`.
Will the endpoint to get a single `LedgerEntry` by its `id` be introduced later? (Such an endpoint looks natural)
For now, if we want to retrieve a particular `LedgerEntry`, we need to store its `create_date` and then call a list endpoint with `min_created` and `max_created` with it.

**Comment by etsyachristensen** [comment]
That's a great point. We should have that as an endpoint. The intention originally was to streamline these endpoints to have one endpoint serve the data that you used to get from several in V2. So the thought was that you'd just get all the Ledger Entries and you wouldn't need to hunt for one in particular. That said, I think it makes sense to add that endpoint.

I've removed the gist just to make sure we aren't leaving that sitting out there. I'll continue to develop out what I've started and finish adding in the refund data on receipts so that we can close this ticket out. I'll add an internal ticket in here in regards to adding the singular endpoint.

**Comment by etsyachristensen** [comment]
@zoborg @shoecake @evangelosdaniil @sergey-chegaev @andriuspuskorius @samborambo305 @multiorders 
Ok after a lot of discussion and work this is now in production. Please see the [release notes](https://github.com/etsy/open-api/releases/tag/3.0.0-general-release-2022-06-02) for what all we've added to the endpoints. I am hopeful that the changes will provide the information you've all been waiting for.

**Comment by samborambo305** [comment]
Thank you, will take a look @etsyachristensen

**Comment by andriuspuskorius** [comment]
Great! Thanks, @etsyachristensen !

**Comment by evangelosdaniil** [comment]
Thank you @etsyachristensen for all the help!

**Comment by multiorders** [comment]
Looking good, @etsyachristensen.
Thank You.

**Comment by sergey-chegaev** [comment]
I guess, our issue is resolved now. Thank you @etsyachristensen!

**Comment by etsyachristensen** [comment]
@sergey-chegaev I've added the singular ledger entry lookup endpoint here: https://developers.etsy.com/documentation/reference#operation/getShopPaymentAccountLedgerEntry

**Comment by samborambo305** [comment]
@etsyachristensen Do you know if there's a way to generate a URL to a listing given a Product_id or listing_id?

**Comment by Gareth064** [comment]
Should be pretty easy using the listing_id.

I think the URL is standard across the board for listings. Just append the listing_id on the end of this URL

https://www.etsy.com/uk/listing/{listing_id}

**Comment by etsyachristensen** [comment]
There's no way with just a product_id, but with the listing_id yes as @Gareth064 said, just take the base url for your region, such as uk in Gareth's example or just https://www.etsy.com/listing/{listing_id} for the US. The rest of the URL you see in the Etsyweb is really there for SEO and tracking metric stuff. You can do it with just the listing_id.
