### ISSUE TITLE
[BUG]: Translations are cleared after calling PUT updateListing

### ISSUE THREAD

**Issue by chrismccaw** [etsy/open-api#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have a listing with translations and then update the main listing title via the v3 API the translated values are cleared out

### Steps to reproduce

1. Add a translation https://www.etsy.com/your/shops/me/languages-translations (I did German)
2. Go to any listing and add title, description to the listing translation
3. Call the update listing v3 endpoint with a title change
4. Refresh the listing UI and you will see the translated values for title and description have been removed.

### Expected behavior

Translations should not be touched unless going via https://developer.etsy.com/documentation/reference/#operation/updateListingTranslation

**Comment by etsyachristensen** [comment]
@chrismccaw At the moment, the behavior is intentional. The expectation is that if a title or description is changed, the shop owner should supply new translations for all other languages they support. There’s a very strong reason for this in that our systems have a machine translation capability but they learn from the seller provided translations. So if you change something in one language but don’t update the corresponding language, the machine learning can take a hit. Even if there’s no substantive change to the translated text, it’s important to force the translations to be re-submitted in hopes that the change will be reflected in the new translation. On your end, prior to updating a listing, it would make sense to first pull the listing translations down and save before submitting the update. Then prompt the seller to review the previous translations and re-submit them.

**Comment by yovasx2** [comment]
Could u point me to the latest note about translations, please?

**Comment by yovasx2** [comment]
Thx. To clarify translations are not wiped out anymore correct?

**Comment by etsyachristensen** [comment]
correct
