### ISSUE TITLE
[BUG]: CORS headers not present

### ISSUE THREAD

**Issue by claudiamatosa** [etsy/open-api#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello there,

I'm trying to call the listings endpoint, which doesn't require oauth, but keep getting a CORS error, due to authorisation headers not being present in the response. I developed my application with web security disabled because I thought it was due to my referrer being localhost, but once I published the website, the same thing happens.

With web security disabled on chrome, the request goes through and I can see my shop items.

Would someone be able to help? What am I missing?

Thank you so much for reading

### Steps to reproduce

Here's a CURL of the request (api key hidden).

```
curl 'https://openapi.etsy.com/v3/application/shops/33935052/listings/active' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: application/json' \
  -H 'Referer: https://claudiamatosa.com/' \
  -H 'x-api-key: HIDDEN' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```

### Expected behavior

I would expect to receive a response with listings from my shop.

**Comment by etsyachristensen** [comment]
@claudiamatosa I'm not able to duplicate the issue you're experiencing. I've used your shop and removed the auth tokens from my Postman application. Here's the curl that's being sent:
```
curl --location --request GET 'https://openapi.etsy.com/v3/application/shops/33935052/listings/active' \
--header 'x-api-key:[hidden]' \
```

So the CORS error has to do with javascript connecting to a remote server. This is a browser security issue. When you disabled the security it allows your browser running on your machine to connect to our server. Without that, Chrome blocks you because Javascript isn't designed to run that way without some specific coding that would require us to allow anyone to access without security. Unfortunately this won't work. Your option I believe would be to build some server-side code (such as using PHP or Node). A script that's not in the browser does not have a CORS issue. Your browser javascript would query your local script (since it's on the same "domain"). That script would connect to the Etsy API via cURL connection to get the data and return it back to your javascript function. The issue is the browser not the API.

I hope that helps!

**Comment by claudiamatosa** [comment]
Yeah, it does, and thank you for the quick reply! So I hear that the api isn't designed for using through a browser, I'm assuming that it's to avoid exposing the keystring. I think it may be worth adding something to the docs, especially the quickstart section, mentioning that the api is only meant to be used server-side.
