### ISSUE TITLE
[BUG]: createShopShippingProfile requires a destination, the docs say it shouldn't

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I don't know if this is a doco bug or an API bug, but something is amiss.

From the documentation for `createShopShippingProfile`:

* destination_country_iso | string <ISO 3166-1 alpha-2>Default: null  The ISO code of the country to which the listing ships. If null, request sets destination to destination_region

* destination_region | stringDefault: "none"Enum: "eu" "non_eu" "none"  The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none", request sets destination to destination_country_iso, or "everywhere" if destination_country_iso is also null

The `destination_region` doc indicates that the value should be "everywhere" if destination_country_iso is also null. However, if I leave destination_region and destination_country_iso unspecified in this call, I get:

400: {"error":"You must provide either a destination_country_iso code or a destination_region."}

I'm pretty confused by why there's a destination here at the shipping profile level since we create explicit ShippingProfileDestinations. How does the top-level setting interact with the specific destinations?

### Steps to reproduce

Call createShopShippingProfile without a `destination_region` or `destination_country_iso`.

### Expected behavior

Seems like there should be no destination region or country at the top level, since those are specified as ShippingProfileDestination objects. The docs seem to indicate it isn't necessary. If I'm expected to do pass a destination, it's not clear what it should be. I'm confused.

**Comment by etsyachristensen** [comment]
@stickfigure We are looking into this. Will update you soon.

**Comment by etsyachristensen** [comment]
@stickfigure I have discussed internally and we have determined we have to adjust the documentation. We have to require at least one of those values for each destination. The idea of omitting both destination country and destination region was that it would mean “everywhere else”. But the issue is that you can only submit one set of carrier + class, which is either domestic OR international, and not both. We couldn't validate and store the shipping info for both, so we require it to be one. You  would have to submit one first, and then create additional entries for other destinations.

We will make changes to the documentation next week to reflect this and explain as I have above. Sorry for the issue. I'll leave it open for now to remind me to work on it first thing next week.

**Comment by stickfigure** [comment]
ok. Does that mean when passing a destination to createShopShippingProfile, it auto-creates one ShippingProfileDestination? I don't see the destination in the json for the profile (at least not in the docs).

If it does, what happens if I create another ShippingProfileDestination for the same destination? Is there some sort of uniqueness constraint on {shipping profile, destination} to avoid duplicates?

Sorry I'm not quite sure how this is supposed to work - though at the moment I do have it working by passing in US destination info for the shipping profile. And explicitly creating the US destination. Not sure if that's good or bad :-)
