### ISSUE TITLE
[DOCS]: uploadListingImage gives bad/wrong examples

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/tutorials/listings#adding-an-image-to-a-listing

### What would you like to change?

The documentation tells you to url encode the parameters and gives an image that is base64 encoded.  This is all wrong.

Even if this example technically works because Node takes the urlencoded data and converts it into a proper multipart form, the documentation should actually tell you to do the right thing and make a multipart form request.  It is highly misleading and just a REALLY bad example in the documentation.

Please give a proper example with a real multipart form and image data that is NOT base64 encoded.

### Why are you proposing this change?

I have spent hours trying to follow the instructions, doing research, and trying to figure out what I am doing wrong just to find out that the examples in the documentation are what is wrong.

**Comment by etsyachristensen** [comment]
Thanks for your feedback @DemiImp. I'm sorry you've spent so much time, but our documentation is actually correct. Since we are using PHP Curl, we do show using multipart/form-data as the Content Type:
![image](https://user-images.githubusercontent.com/83842847/153510168-ee218369-e2d0-48e2-a6e1-f52ac1f863eb.png)

As for the encoding, this is how we have to encode the image in order to pass it as a post field. Alternatively, we could change it to an array with image being one of the nodes of the array and use CURLFILE() with a file path. However this could have led to much more confusion so we opted for the most simplistic approach.

I'm sorry I don't have better news for you. But please feel free to reach out for help when you run into issues. This github repo is beginning to gain traction with the other developers and they are starting to help with answering questions, sometimes even before we can.

**Comment by DemiImp** [comment]
Thanks for responding!

The problem isn't the content-type, but rather this:

```
var urlencoded = new URLSearchParams();
urlencoded.append("image", "vvkdljkejlluvujfnjvjftghdkufgvvkd...
```

This is highly misleading and looks like the body of the request should be URL encoded.  Again, even if the example "technically works", it is a terrible example and is confusing.

**Comment by etsyachristensen** [comment]
Gotcha. Yeah this is an area that I'm not an expert in as it's a JS Fetch example. I'll have to see if any of our JS people can look at it. The image upload via JS has long been a thorny spot, but not because of docs. Different JS frameworks do things differently. I recall seeing some one post how they did it in Axios and another maybe in Express or something. If I can find someone on staff that's more familiar with this part I'll have them review this element of the document and make changes if need be.

**Comment by jmarcv** [comment]
It would be nice if the docs discussed the required encoding.  Using PHP curl, I am using base64_encode and the output doesn't look like your example.  It also does not work.
So what IS the encoding required? 'binary' doesn't tell me much.
