### ISSUE TITLE
[BUG]: Inconsistent field labels for processing+delivery

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documentation on this page:
https://developer.etsy.com/documentation/reference/#operation/createShopShippingProfile

Conflicts with the documentation on this page:
https://www.etsy.com/developers/documentation/reference/shippingtemplate#method_createshippingtemplate

On API v3, we have the fields:
```
min_processing_time
max_processing_time
min_delivery_days
max_delivery_days
```

These fields conflict with API v2:
```
min_processing_days
max_processing_days
min_delivery_time
max_delivery_time
```

### Steps to reproduce

Check the documentation links

### Expected behavior

Everything should be labeled the same way on both APIs.

For example:

```
min_processing_days
max_processing_days
min_delivery_days
max_delivery_days
```

**Comment by etsyachristensen** [comment]
This isn't something we can change at this time. The V3 API was created very specifically with this wording because processing typically would take less than delivery. So we did processing as "time" and delivery as "days". If they both said "days" it would be more confusing.

**Comment by DemiImp** [comment]
Don't close it yet!  It's not just that it's time and days!

One says min_processing_time the other says min_processing_days.  I'm asking at the very least to unify the field names!

I am 100% ok with both of them saying the same thing!  The prompt when creating the ticket asked for what I would do.  You don't have to take my suggestion.

Please just fix that API v2 and API v3 flipped the days+time on their fields!

**Comment by DemiImp** [comment]
For example, change API v2 to be:

```
min_processing_time
max_processing_time
min_delivery_days
max_delivery_days
```

**Comment by etsyachristensen** [comment]
In order to "fix" that we would have to introduce some significant breaking changes either to V2 or V3. We aren't prepared to do that at this point. Again, when the team build API V3, it was intentionally changed. I realize it's a departure from V2, but that's kind of the point. We are trying to build V3 with intention on as much sensible naming logic that we can reasonably provide and make it better, faster and more extensible. There will be growing pains of course but that will just help this version of the API get better.
