### ISSUE TITLE
[BUG]: Server error when updating listing

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling updateInventory on a specific listing I get a general error with this message:
{"error":"Server Error"}

Can you advice on how to troubleshoot such error?

Thanks,

### Steps to reproduce

Call the updateInventory on a listing

### Expected behavior

Quantity should be updated or at least an informative error message should be returned

**Comment by nmrdxt** [comment]
Happens here as well :/It does not happen on all requests, but it happens enough that it affects performance. 

I would get it on various endpoints, getListingInventory, getShopReceipts, updateListingInventory and more. 

It looks like it started happening for us since Feb 12th (it also happened between Feb 8th-9th).

**Comment by etsyachristensen** [comment]
I have a fix for the `updateListingInventory` and `getShopReceipts` endpoints. It has to go through testing on Monday morning and will hopefully end up in production midday. As for the `getListingInventory` endpoint I haven't seen any errors coming through. @nmrdxt can you share the listing id where you are getting this error?

**Comment by nmrdxt** [comment]
Happy to read there is a resolution coming! Thanks!

I'm unable to find the getListingInventory error (I'll keep looking), but I did find a server error for the getListing endpoint (listing ID 1110248331). 

Thanks again.

**Comment by thebest0f** [comment]
> I have a fix for the `updateListingInventory` and `getShopReceipts` endpoints. It has to go through testing on Monday morning and will hopefully end up in production midday. As for the `getListingInventory` endpoint I haven't seen any errors coming through. @nmrdxt can you share the listing id where you are getting this error?

Could you update this post when that happens? We have updateListingInventory blowing up quite a bit.  Would appreciate it.

**Comment by etsyachristensen** [comment]
@nmrdxt It's in process of testing now. I hope to have it out soon. On that `getListing` error, I'm not able to duplicate that. Are you doing any includes (associations) when pulling that listing?

**Comment by etsyachristensen** [comment]
@nmrdxt @assaflei and @thebest0f I've had to revert the changes I made for preventing the variation images from being wiped when updating inventory. The fix for the `updateListingInventory` endpoint is up now as well as the `getShopReceipts` endpoint. I'll revisit the variation images again tomorrow.

**Comment by nmrdxt** [comment]
Fantastic! Thank you so much for taking care of this. That's a relief. I'll continue monitoring our logs, and notify if I notice any similar errors. Thanks again.

**Comment by yovasx2** [comment]
inventory working for me like a charm, thanks @etsyachristensen

**Comment by etsyachristensen** [comment]
@yovasx2 @assaflei @thebest0f or @nmrdxt Do any of you happen to have a record of a listing id that was causing the error to show up over the weekend? I have the errors logged but don't have a listing id. I need to do some investigation into why it was happening in order to get the inventory update to not wipe variation images out. Thanks!

**Comment by assaflei** [comment]
@etsyachristensen I sent an email with details to developers@etsy.com as soon as I opened the issue, few days ago, can you verify it's received? I didn't get any confirmation

**Comment by assaflei** [comment]
I can update that the listings with the updateInventory error were now updated successfully

**Comment by nmrdxt** [comment]
@etsyachristensen Is the issue with variation images resolved? We've gotten reports a few days ago related to variation images being shuffled after inventory update is attempted. I did not realize that it could be connected to the 'Server Error' issue until I reread your last message - could you please give an update regarding the variation images? Thanks!

**Comment by etsyachristensen** [comment]
@nmrdxt See #200 . I had to roll back the changes briefly due to the above issues. I've got it fixed and in testing today. I hope to have it in production today. Sorry for all the trouble.
