### ISSUE TITLE
[BUG]: Shipping method is not returned with orders/receipts in V3 API

### ISSUE THREAD

**Issue by main24** [etsy/open-api#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chosen shipping method is not returned with orders via V3 API anymore. The documentation states that shipping method is now returned in transactions, however it is always blank, however it is being returned via V2 API. Checked the following API endpoints:
* [getShopReceipt](https://developer.etsy.com/documentation/reference/#operation/getShopReceipt)
* [getShopReceipts](https://developer.etsy.com/documentation/reference/#operation/getShopReceipts)
* [getShopReceiptTransaction](https://developer.etsy.com/documentation/reference/#operation/getShopReceiptTransaction)

Example order: 2313911164
V2 API returns: `Standard Shipping`
V3 API returns: `null`

### Steps to reproduce

1. Make a request to [getShopReceipt](https://developer.etsy.com/documentation/reference/#operation/getShopReceipt) with receipt id `2313911164`;
2. Check `transactions` array, find `shipping_method` attribute.

All transactions return blank `shipping_method`. 

### Expected behavior

All transactions of the example order should return `shipping_method: "Standard Shipping"`

### Additional context

Set of auth permissions/scopes is the same for V2 and V3 -- requests have been made using the same V2 auth token. Attempted to grant `shops_rw` via V2 API -- it haven't influenced V3 response.

**Comment by main24** [comment]
Any updates on this please? It's one of the stoppers of migration to V3 for us.

**Comment by Gareth064** [comment]
@main24 if you look at #271, which was closed as resolved, it describes that the **Shipping_Method** will be NULL if there was no upgraded shipping selected, so you can infer that by it being NULL that it is Standard Shipping.

But this doesn't make sense when you look at the properties of the **ShopReceiptTransaction** schema for the API.

You can see here that there is already a **Shipping_Upgrade** property to hold the upgrade information

![image](https://user-images.githubusercontent.com/22307223/158903027-7a3050bf-df35-4f13-8e70-dfa98a58227e.png)

And in fact, the description of the Shipping_Method says its the name of the selected Shipping Method.

@etsyachristensen can you comment further on this please. Is your statement on #271 still true to this day, considering that issue was closed back in November and a lot has change with the API since.

**Comment by main24** [comment]
Thank you @Gareth064, missed https://github.com/etsy/open-api/issues/271 previously.

I guess `shipping_method` is redundant in the response as it seems to be always `nil`, or I'm missing something yet another use case?

**Comment by Gareth064** [comment]
No worries @main24 . Hopefully @etsyachristensen can update on the situation soon.

**Comment by main24** [comment]
Closing the issue as current logic has been clarified.
