### ISSUE TITLE
Etsy varients updation using V3 API

### ISSUE THREAD

**Issue by edwinjoy69** [etsy/open-api#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://stackoverflow.com/questions/61806234/etsy-api-update-inventory

### What would you like to change?

There is no option to update new property for a product or add new variation style to a product by using api.I think there is option in etsy v2 API not in etsy v3 api.please share your thoughts.?

### Why are you proposing this change?

Please show me the option to add new varients and propertys from api.

**Comment by etsyachristensen** [comment]
I'm not sure I follow completely but if I am, in order to add new variants to a listing you have to post it as full part of the inventory. So if you already have some variants, pull your current listing inventory and then add the variant into the inventory array and post that back to the updateListingInventory endpoint (https://developer.etsy.com/documentation/reference/#operation/updateListingInventory)
