### ISSUE TITLE
[BUG]: getListingsByShop returns invalid Shipping ID

### ISSUE THREAD

**Issue by thisisjake** [etsy/open-api#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

GET request to "https://openapi.etsy.com/v3/application/shops/{shop id}/listings" returns incorrect shipping ids for all listings

This bug has been introduced in the last 14 or so hours.

None of the shipping ids exist within the store.

### Steps to reproduce

GET request to "https://openapi.etsy.com/v3/application/shops/{shop id}/listings" returns incorrect shipping id

### Expected behavior

Correct shipping id should be returned.

EXAMPLE:
Listing ID: 706862566
Shipping Profile ID (according to the website): 109483997919 (correct as of 14 hours ago or so)

API Returned Shipping Profile ID: 9809193

**Comment by etsyachristensen** [comment]
There was a change pushed earlier today. It's being reverted now. Will revise and fix the change tomorrow.

**Comment by thisisjake** [comment]
@etsyachristensen thank you, really appreciate your prompt response and action.

On a side note, I tried to check if there were any changes before sending my bug request, I couldn't see anything posted in the releases or any recent commits. I'm guessing I can't see that sort of information through github then? Thanks again!

**Comment by Gareth064** [comment]
> On a side note, I tried to check if there were any changes before sending my bug request, I couldn't see anything posted in the releases or any recent commits. I'm guessing I can't see that sort of information through github then?

This is what I have been saying lots of times on many threads in here. Things are being changed or fixed without any proper comms about it. I seen Andrew mention on another issue last night (UK time) that he had pushed a fix to Prod, and I'm certain its the is the thing that probably caused you to raise this bug.

It's is a very bad experience for us who want to Develop apps against Etsy when the API can have changes made to it at any point in time, and the "communication" of that change is a footnote on a issue on here. I appreciate its a very agile approach, but because we (the API consumers) don't have proper visibility of the work the Etsy Dev team is doing, then we just get left in the dark with changes unless we go digging through threads on here to see if and changes are mentioned.

Etsy need to get a proper Developer Instance for us to use and for them to push changes to for "us" (or at least the person who raised the bug) to test before it gets pushed to Prod. Then maybe only push to Prod on a fixed cadence like once per week... finally with every push to Prod, there is an announcement added to the Releases page here on GitHub to inform us all what has changed. Or even better, we get an announcement to say a change is going to happen in Prod to give us a heads up.

I'm a big fan of Etsy and I'm excited to be building apps to integrate with it, but this experience is just awful in comparison to any other established ecommerce platform out there.

@nateswart I am gonna mention you here again since you were the only who responded to some of my other posts about the lack of proper comms. It was December last year [that you said](https://github.com/etsy/open-api/issues/149#issuecomment-1003055036) that you were working on a better comms strategy and maybe with the exception of the Release page, nothing appears to have changed which actually help us developers keep ontop of what you are doing, changing, fixing or planning.

**Comment by etsyachristensen** [comment]
@thisisjake We have corrected the bug and put the fix into production. Please check your listings and let me know if you continue to have issues.
