### ISSUE TITLE
[FEATURE]: Support "Courier Express" carrier and make it trackable on Etsy

### ISSUE THREAD

**Issue by NSaikevych** [etsy/open-api#465]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Etsy has warned our merchants about the “no tracking status for order” that could harm their accounts. 

In this case, it is related to [Courier Express](https://courierexpress.net/) shipping carrier.

### Describe the solution you'd like

It would be great if Etsy added this carrier to the supported and trackable carriers list.

### Describe any alternatives you've considered

To extend Etsy v3 API functionality to allow providing the tracking_url (via [track.easypost.com](https://track.easypost.com/)), so it will be possible to track whatever shipping carrier.

**Comment by etsyachristensen** [comment]
@NSaikevych Can you provide an example tracking code for this carrier (it doesn't have to be a legitimate code, just formatted so that we know what to expect)? Also a url that would be used to track this code. We don't do the tracking inside of Etsy, but we provide links out to the carrier's site (or whatever 3rd party) for their tracking system. We use Aftership.com for many of our existing carriers. So their URL would be something like this: https://www.aftership.com/track/9400111202508299673168

**Comment by etsyachristensen** [comment]
I can say that we can't provide an integration with EasyPost. But if they have a URL that we can link users to with the tracking code, then we can add Courier Express to the carrier list.

**Comment by NSaikevych** [comment]
@etsyachristensen Thank you for your answer. Do I understand correctly that if Aftership does not support this carrier, Etsy could not support tracking as well?

**Comment by etsyachristensen** [comment]
No that's not what I mean. We use Aftership for many of the carriers simply because we can formulate the URL to track the package. Some carriers you have to go to a page and enter a tracking code and press a form submit button. With Aftership it's just a common url with a tracking code at the end.

If you can't get a URL for tracking, we may still be able to add them and you can still enter the tracking code. There just wouldn't be a link to follow to track the package. The user would have to copy the code and know where to go to track it.

**Comment by etsyachristensen** [comment]
Yes. Sorry. I am hoping to get on that this week.

**Comment by etsyachristensen** [comment]
@NSaikevych We have added support for Courier Express to the shipping companies.
