### ISSUE TITLE
[BUG]: updateListing state results in unexpected behaviour

### ISSUE THREAD

**Issue by cal-tec** [etsy/open-api#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you submit
{"state":"incative"} to the updateListing endpoint for a listing the result is that the listing enters the "edit" state not a state of "inactive"

### Steps to reproduce

make a put request to updateListing endpoint for a listing with the following data {"state":"incative"}

### Expected behavior

The result should be that the listing changes its state to "incative"

### Additional context

My scenario is inventory updates on listings with variations.....

I can not submit an inventory update for a listing with variations if the total quantity available is 0.
The ideal and correct scenario would be to set the listing state to "sold_out" but this is not possible as documented in [Issue 395](https://github.com/etsy/open-api/issues/395).
Therefore the only way to do this seems to be to implement the workaround given in [Issue 395#issuecomment-1063149284](https://github.com/etsy/open-api/issues/395#issuecomment-1063149284) and this is confirmed by @etsyachristensen .
The problem is it does not work as expected or documented which has further implications on our system design.
If the listing enters an "edit" state there is no way of distinguishing it from other listings that are genuinely in the "edit" state or identifying it as a listing that is actually "sold_out" (which is the goal in this use case).

Please fix this bug asap. On top of the various bugs, There are several design issues with this API which I have already raised in the past. It is hard to work with and therefore it does not really fulfill its purpose.

There should be an easy way to update stock levels, uploading listings with variations or no variations to a 0 stock level should automatically put the in a "sold_out" or "out_of_stock" state. Having to make calls to set listings to "inactive" to effectively 0 the stock is madness, especially when "incative" is contextually the wrong state for the listing to be in... and even after jumping through all these rediculous hoops and processes for a simple task the API is not making the state change as documented.

Please Please Please get your act together Etsy, there is simply no excuse for providing such a poor set of tools to your customers.... Yes sellers are customers and therefore developers and consumers of this API are also customers....

**Comment by etsyachristensen** [comment]
@cal-tec On our end, the "inactive" and "edit" states are synonymous. When you set a listing to inactive, it's actually in "edit". This is an old legacy nomenclature that simply hasn't been updated. Originally, the idea (from what I've gathered - I wasn't here back then) was that once a listing went active, the ability to edit the listing was severely limited. You had to deactivate the listing (putting it into "edit" mode) in order to make changes to the listing.

As for setting the product to "sold_out" I'm sorry we can't accommodate that request. It's a built-in feature of our system to control the inventory and ensure that we don't have millions of listings sitting in our database as "active" but sold out. This can affect performance of searches and other processes. We want to be sure to maintain a robust active market without the clutter of stale old listings that aren't being updated and handled by shop owners.

I'll try not to take your final paragraph too personally. I joined the team a year ago, about a year or so into development of the V3 OpenAPI. While you may not agree with some of our approaches, we are proud of the work we've done taking on the huge task of updating the aging OpenAPI. There is certainly still some work to be done to make new features available and simplify some of the endpoints and we acknowledge that.

If you are certain you could do better building an enterprise level API against a massive data set, Etsy is always hiring! https://careers.etsy.com/global/en/c/engineering-jobs
