### ISSUE TITLE
[BUG]: Few Mandatory Informations Are Missing in V3 compared to V2.

### ISSUE THREAD

**Issue by IamPARAMESH** [etsy/open-api#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. In getShopReceiptTransactionsByReceipt as well as getShopReceipts V2 API, Inside transactions array we used to receive **non_taxable node under Listings array** which has been removed in V3 which is causing issue in our workflow.

2. We are **unable to find Rate Limits** for **Token Fetch API Call(/public/oauth/token)**, we will be using it very frequently for every user to get access_token from refresh_token. We need to know is there any limits at **user level or application level** as we are sending client_id in the request.
 
3. Can we rely etsy user_id from the access/refresh token beginning part?

4.  We could read that refresh_token has validity of 90 days. What if we used later to that? and do we need to reautenticate again to get refresh_token ?

5. When OAuth 1.0 authentication will be deprecated? And can we able to get any extentions for API Version migrations?

### Steps to reproduce

1. We can execute getShopReceiptTransactionsByReceipt and getShopReceipts APIs in both V2 and V3 and we find the difference between missing nodes like (Listing(non_taxable))

2. https://api.etsy.com/v3/public/oauth/token API rate limits per Application and user levels need to be clarified

### Expected behavior

Please refer description

**Comment by etsyachristensen** [comment]
@IamPARAMESH 

1. We don't return the listing as an object in the receipt/transaction endpoints in V3. We do provide the listing_id though so you can query `getListing` endpoint to get the listing data. Inside the listing array returned by the get endpoints for listings, you will have `non_taxable` and `is_taxable`.

2. The rate limit information is returned in the headers sent back by the API. Below is a screenshot from Postman showing what they look like. You can read more about this here: https://developers.etsy.com/documentation/essentials/rate-limits/
![image](https://user-images.githubusercontent.com/83842847/170058526-3df71a80-e86a-48d1-83b5-25700a8b8db9.png)

3. Yes. In OAuth 2, our tokens are prefixed with the user id that requested the token.

4. The refresh token is good for 90 days yes. But you will get a new refresh token every time you refresh the token. The access tokens are only good for one hour so your app will likely be refreshing the token regularly. If for some reason a user is absent from using your app for 90 days or more and the refresh token expires, you will have to go through the OAuth process again. You DO NOT have to have your shop owner go through the approval process. You can simply fetch a new token.

5. We don't have a firm timeline for deprecating OAuth 1.0. We do plan to make it so that apps using V3 of the OpenAPI will only be able to use OAuth 2 tokens fairly soon.
