### ISSUE TITLE
[BUG]: use getListingsByShop v3 APi  retrieving 0 records

### ISSUE THREAD

**Issue by superxaiogu** [etsy/open-api#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1、I have 'active' two listings and  two 'draft' listings, but the v3 APi getListingsByShop  does not get the data.
2、My store is in development mode, but why is my store in holiday mode again? Is this the reason why I can't get the data? If so, how can I get the data? I  think the developer account Should not have this restriction

### Steps to reproduce

url: https://api.etsy.com/v3/application/shops/35072348/listings
param: limit=10&offset=0

### Expected behavior

Run a valid query against our shop listings

**Comment by etsyachristensen** [comment]
I just checked our system and we show the shop `35072348` as being closed with no listings. Are you sure that id is the shop id or could it be the user id?

**Comment by etsyachristensen** [comment]
@superxaiogu and @NickSealer I believe the issue is that your shops are set to "Not Searchable" as requested by the shop owners. The "find" endpoints use our search mechanism so you can pass in keywords. If you simply need to list all the listings for the shop that are active you can use the `getListingsByShop` endpoint here: https://developers.etsy.com/documentation/reference#operation/getListingsByShop

If you're needing to search by keyword with pagination and sorting etc, then you'd use the find endpoint. But the shop must be searchable.
