### ISSUE TITLE
[DOCS]: "Edit" Listing State

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/tutorials/listings#listing-lifecycle-and-state

### What would you like to change?

I would like to see the `edit` listing state to be described in the docs.  I don't see it in the Listings Tutorial and I don't see it in the listing state enums in the API reference manual.

### Why are you proposing this change?

This state is mentioned in the v2 listing docs, but isn't in the v3 docs. This leads the reader to think that the `edit` status isn't in v3 at all - which in fact it is.

**Comment by etsyachristensen** [comment]
Apologies @NathanConroyOrd. The `edit` state is actually a legacy term we use for `inactive`. It's still used in various places, but essentially it just means that the listing is no longer `active`, but not `sold out` or `expired`. Since you can't move a listing from `active` to `draft`, when you move to `inactive` it goes into that `edit` state. I'll see if we can get this documented somewhere.
