### ISSUE TITLE
[BUG]: invalid_token error

### ISSUE THREAD

**Issue by amitshuklaCedcoss** [etsy/open-api#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

getting invalid token when calling any API like  [getShopReceipts](https://developers.etsy.com/documentation/reference#operation/updateShopReceipt)

```
{
    "error":"invalid_token",
    "error_description":"access token is expired"
}
```
then when trying to refresh token **[Requesting a Refresh OAuth Token](https://developers.etsy.com/documentation/essentials/authentication/#requesting-a-refresh-oauth-token)**
getting error as **refresh_token is revoked** 

```
{
    "error": "invalid_grant",
    "error_description": "refresh_token is revoked"
}
```

### Steps to reproduce

this error comes randomly, no pattern found  yet

### Expected behavior

it should return 
```
access_token
refresh_token
```

### Additional context

[https://api.etsy.com/v3/public/oauth/token](https://api.etsy.com/v3/public/oauth/token)

> "shop_id":10051834
```
grant_type:refresh_token
client_id: {x-api-key}
refresh_token:53888612.5iDmNC6vbkg5jAh-5KfbSEyP228ZjGfgbGNCQnLPFfyMfT4EDYsQdg4ZQdbl8iEYv5RbxbuT9gLcd5oeLk3HATkQ6uV
```

@etsyachristensen please check this concern. 
thanks

**Comment by etsyachristensen** [comment]
@amitshuklaCedcoss A security change was made to the core of Etsy system on June 15th. If a user changes their password, it invalidates all tokens. This is an intentional change.

I found out about this yesterday and we are working through the issue. But for the moment, you'll need to ask your users that face this issue to re-validate your app.

**Comment by amitshuklaCedcoss** [comment]
> I found out about this yesterday and we are working through the issue.

@etsyachristensen when we can suppose to get some solution to it?

**Comment by Deepshikha-cedcoss** [comment]
@etsyachristensen  I need your help. Actually, we're facing invalid token errors with a lot of the sellers and not able to understand any pattern in which case we have to re-validate the app again because we're getting different types of responses for one Seller on different API calls. here below I've mentioned the responses in the "invalid_token" case and also the SHOP_ID

1- getting this response, when calling ([getShopShippingProfile](https://developers.etsy.com/documentation/reference/#operation/createShopShippingProfile)) API call
     --  {
            "error":"invalid_token",
            "error_description":"access token is expired"
       }
2- getting this response, when calling [getShopReceipts](https://developers.etsy.com/documentation/reference/#operation/getShopReceipts) API call
     -- {
            "error":"invalid_token",
            "error_description":"access token is revoked"
        }
3-and then, trying to refresh token getting the **error "invalid_grant" and message "refresh_token is revoked"**.
{
    "error": "invalid_grant",
    "error_description": "refresh_token is revoked"
}

Additional info-
SHOP ID  = 12782207,
["X-Etsy-Request-Uuid"] =  "EuRIJd1-r54zxHvFsKm8xxGd4Ucb"

@etsyachristensen please provide guidance for handling or understanding the cases in which case we need to re-validate the app

**Comment by etsyachristensen** [comment]
@Deepshikha-cedcoss The issue at least with this one shop is that they changed their password. When passwords are changed in our system, all tokens get revoked. They will have to re-authorize the app. I suspect that is happening with many of the shops.

**Comment by etsyachristensen** [comment]
If you can give me a list of shop ids I can look into them and verify if it was a password change that revoked the token.

I am not sure why you got the "access token is expired" on the shipping endpoint though. I'll have our oauth people look into that one.

**Comment by Deepshikha-cedcoss** [comment]
@etsyachristensen Thanks for the update. There is some shop_id which I have mentioned. You can check further on that.
  
SHOP_ID = [30180781, 13581174]
Expected_output:-
if any seller's token has been revoked, then in this case only "access token is revoked" error will occur instead of "access_token is expired"

**Comment by Deepshikha-cedcoss** [comment]
@etsyachristensen please check this concern

**Comment by nmrdxt** [comment]
Hello,

Just came to say that this invalid_token error seem to be getting out of control. Errors appear to be random (from my end at least), and the number of shops it happens to is too long to list. 

This can result in extreme inconvenience for merchants that uses apps that rely on continuous communication with Etsy (order fulfillment and similar). I really hope a resolution is in the horizon. Thank you very much!

**Comment by Deepshikha-cedcoss** [comment]
@etsyachristensen any update on this? It's been more than a month now but no update yet. 

I've mentioned some shop IDs to check. please check
**[14404636,34158977,37369346,26800331]**

**Expected_output:-**
If any seller's token has been revoked, then in this case only "**access token is revoked**" error will occur instead of "**access_token is expired**
