### ISSUE TITLE
[ENDPOINT]: ShopListing object to contain includable relationships from queries 

### ISSUE THREAD

**Issue by tjoyal** [etsy/open-api#541]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

I am relatively new to the internals of open-api so let's keep that in mind.

It seems as per [this issue](https://github.com/etsy/open-api/issues/96) or [this issue](https://github.com/etsy/open-api/issues/236) the "includes" relationships I was looking for have been recently added to the query API layer.

Eg.: https://developers.etsy.com/documentation/reference/#operation/getListingsByShop
```
Array of strings
Default: ""
Items Enum: "Shipping" "Images" "Shop" "User" "Translations" "Inventory"
An enumerated string that attaches a valid association. Acceptable inputs are 'Shipping', 'Shop', 'Images', 'User', 'Translations' and 'Inventory'. 
```

That being said, the `ShopListing`  object definition (`components.schemas.ShopListing` from https://www.etsy.com/openapi/generated/oas/3.0.0.json) does not contain the necessary properties. It only contains the required attributes, not the optional ones based on the queries.

This cascade in an issue for me as I am generating the API stubs via https://github.com/OpenAPITools/openapi-generator where the underlying http response I get does contain the requested includes, but they aren't made available to my code.

### Proposed Endpoint Design Change

Add the different possible "includes" from queries in the `ShopListing` attributes as nullable values. 

There might be a better way to do this, I'm not familiar enough with open-api.

### Why are you proposing this change?

For me the whole idea of using open-api as a consumer is to generate code stubs. 

I would hate to be forced to either not use the `includes` parameters and to do multiple additional queries via the other endpoints or to do raw http instead.

**Comment by etsyachristensen** [comment]
Correct. Those are all done and cover that issue. We've closed that issue.

We're not sure we follow what you are asking for here. The getListing endpoint (and other get endpoints that return the listing resource object) work with those includes. If there is an associated object (or objects) for the listing and you've asked for those in the "includes" input, then you should be getting what you need.

For the optional properties/attributes, we can't possibly guess at what a user might have for those so creating stubs wouldn't really work. Users are able to create a number of possible custom attributes and properties using variations and such. Since we can't guess what a user might make up for one of these, we can't anticipate it.

Am I misunderstanding the request here? Could this be better suited for the Discussions area rather than creating it as an issue since we don't yet have a defined issue here (at least not yet)?

**Comment by tjoyal** [comment]
The operation `"operationId":”getListing"` returns a `"$ref": "#/components/schemas/ShopListingWithAssociations"`. This behaves as expected and the `includes` parameter additinal response fields can be added to the  `ShopListingWithAssociations` object.

Alternatively, the `"operationId": "getListingsByShop"` returns a `"$ref": "#/components/schemas/ShopListingsWithAssociations"`. So far so good.

Where I think things break down is where `ShopListingsWithAssociations` is an Array of `"$ref": "#/components/schemas/ShopListing"` where I think it should be an Array of `"$ref": "#/components/schemas/ShopListingWithAssociations"`

This led to the code generation to miss some of the attributes returned by the http response.

Additionally, you can see this reflected in the documentation.

https://developers.etsy.com/documentation/reference/#operation/getListing will have in the “Responses” section for 200 fields like “images”, “inventory” or “sku” where in https://developers.etsy.com/documentation/reference/#operation/getListingsByShop these fields will not be present.

**Comment by etsyachristensen** [comment]
@tjoyal This has been corrected. Thanks for calling this out.

**Comment by tjoyal** [comment]
Wonderful, everything works as expected, thanks!
