### ISSUE TITLE
[BUG]: Api v3 Patch uploadListing tags

### ISSUE THREAD

**Issue by rexliu0715** [etsy/open-api#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried to use different tags values:

"tags": "Circle,Round,Punch"
"tags": "'Circle','Round','Punch'",
"tags": ["Circle","Round","Punch"]

error:
There was a problem with /tags : You may not have duplicate tags.

"tags": "[Circle,Round,Punch]"
error:
There was a problem with /tags : contains invalid character

<img width="917" alt="Screenshot 2022-08-12 at 17 14 22" src="https://user-images.githubusercontent.com/7487563/184324244-33d345bf-2cd4-4c11-af33-998e85d9f7e8.png">
s

### Steps to reproduce

1. [Patch] https://openapi.etsy.com/v3/application/shops/:shopId/listings/:listingId
2. headers add 'Content-Type': 'application/x-www-form-urlencoded'
3. form -> tags: "Circle,Round,Punch"

### Expected behavior

updated the listing tags and return success.

**Comment by etsyachristensen** [comment]
@rexliu0715 I am not able to duplicate this issue. The proper string would be:

Circle,Round,Punch

No quotes, no brackets.

I can't explain why it's giving you the error without a copy of the payload. Can you post the full payload and just take out your bearer token and api key? The shop id and listing id are already pretty much public info so no need to obfuscate them.

**Comment by rexliu0715** [comment]
Thanks for your reply. I tried to update one of key "tags" as the screen. The params section was empty. Refreshed the token.

<img width="700" alt="Screenshot 2022-08-15 at 10 18 28" src="https://user-images.githubusercontent.com/7487563/184566888-a95bf220-f73e-470e-bbf9-3de62e463835.png">
<img width="1259" alt="Screenshot_2022-08-15_at_10_19_05" src="https://user-images.githubusercontent.com/7487563/18456689
<img width="1255" alt="Screenshot 2022-08-15 at 10 24 52" src="https://user-images.githubusercontent.com/7487563/184567199-525dbad8-5637-4d6d-a582-f9b666c84f34.png">
0-8e5a4850-66c3-42a7-9e01-ef6a51c3286c.png">
<img width="1256" alt="Screenshot 2022-08-15 at 10 25 04" src="https://user-images.githubusercontent.com/7487563/184567212-f4c6afb8-c28c-4726-994a-703cb829e637.png">

**Comment by rexliu0715** [comment]
@etsyachristensen  please help.

**Comment by rexliu0715** [comment]
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'tags': 'circle,Round,Punch' 
});
var config = {
  method: 'patch',
  url: 'https://openapi.etsy.com/v3/application/shops/12744295/listings/638009915',
  headers: { 
    'Authorization': 'Bearer user_id.******', 
    'Content-Type': 'application/x-www-form-urlencoded', 
    'Cookie': 'user_prefs=***********'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

**Comment by rexliu0715** [comment]
@etsyachristensen 
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'tags': 'circle,Round,Punch' 
});
var config = {
  method: 'patch',
  url: 'https://openapi.etsy.com/v3/application/shops/12744295/listings/638009915',
  headers: { 
    'Authorization': 'Bearer user_id.xxxxxxx', 
    'Content-Type': 'application/x-www-form-urlencoded', 
    'Cookie': 'user_prefs=xxxxxx'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

**Comment by etsyachristensen** [comment]
I'm not really much of a NodeJS developer but what I did was create a listing similar what you are working with and attempting to write the same data to my listing using Postman. I'm not getting any errors when doing so. I did the same thing and brought up the </> code tab and switched from cURL to "NodeJS - Axios" to see what looks different between mine and yours.

One thing that jumps out at me, and maybe this was intentional, is that you don't have a line in the headers for `x-api-key`. I assume it was there and you removed it for security. Otherwise you should get a different error.

Questions:
1. Does this only happen when only updating tags? If you update any other fields at the same time does it still throw the error?
2. Is this happening to all listings? Or just this one?
3. Just out of curiosity could you try disabling the "Enable SSL certificate verification" option in the Settings tab in Postman? It shouldn't be an issue but I'm wondering if you'll see a change.

I really would like to help. I'm just not able to duplicate the issue.

**Comment by etsyachristensen** [comment]
@rexliu0715 I just was reviewing the listing and found that in the Polish language translations for that listing there are two entries in the tags for "pasek". This is likely the issue as they are duplicated. While you aren't editing the polish language, our system does look at translations for the shop. Since "pasek" can mean both "belt" and "strap" it does appear that you can use just "pas" for belt. If you can edit the listing in the Shop Manager and change one of those to just "pas", save and then attempt your update via API again, you will probably have better luck.

I will mention this to our translation team to look into but it may take some time before this behavior can be corrected.

**Comment by rexliu0715** [comment]
@etsyachristensen thank. you are right. it was works after fix language translations
