### ISSUE TITLE
[BUG]: Invalid API Key

### ISSUE THREAD

**Issue by zknicker** [etsy/open-api#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I maintain an internal app for my team and I to help with our listing posting & management process. This app is not new (1+ years old), but as of this afternoon, it no longer appears to exist. Despite just working this morning, the app is now missing from the developers "your apps" page, and my api key cannot be used to complete any API calls (including OAuth authentication).

Is there an outage on Etsy's side, or did something happen to my app?

### Steps to reproduce

1. Navigate to https://www.etsy.com/developers/your-apps
2. Confirm that your app is not listed

--or--

1. Query for a new refresh token from https://api.etsy.com/v3/public/oauth/token
2. Confirm that the response specifies the error "Invalid API key"

### Expected behavior

My existing API key continues to work when fetching an OAuth token.

**Comment by yovasx2** [comment]
same for me

**Comment by halfluck** [comment]
+1 Same Issue Here

**Comment by kbasali** [comment]
+1 @etsyachristensen

**Comment by juanfernandoe** [comment]
+1 Same issue

**Comment by yovasx2** [comment]
mine was re-stablished

**Comment by huppy** [comment]
+1 
@yovasx2 How did you get re-enabled? Prompting them? Or it just happened?

**Comment by x-bass** [comment]
same

**Comment by yovasx2** [comment]
it was fixed i entered to the URL described above my app was not there and it suddenly appears

**Comment by yovasx2** [comment]
> it was fixed i entered to the URL described above my app was not there and it suddenly appears


it was fixed i entered to the URL described above my app was not there and it suddenly appears

**Comment by benjymouse** [comment]
+1 same issue here too

**Comment by etsyachristensen** [comment]
we had an errant script accidentally trip on something and it deactivated a lot of keys. It's being restored now. Sorry for the trouble. please be patient.

**Comment by cwilkins-godaddy** [comment]
+1 same issue, app is gone, end users are sad.

**Comment by DemiImp** [comment]
@etsyachristensen - Is that why I've been getting oauth_problem=consumer_key_refused?

Please let me know before I make any large changes to my site and service.

**Comment by etsyachristensen** [comment]
@DemiImp Yes. More than likely. We are almost done restoring them.

**Comment by bsom** [comment]
Getting closer.  App is back, but it is now 'Listed' when it isn't supposed to be. :-)

**Comment by etsyachristensen** [comment]
All apps and keys should now be restored.
If you’re still running into difficulties with your app connecting or have noticed that it’s live and shouldn’t be, please reach out to [developers@etsy.com](mailto:developers@etsy.com) with the subject line: 08/16 API issues

**Comment by scuculeac-plenty** [comment]
The problem still exists, oauth_problem=token_revoked from this morning

**Comment by juanfernandoe** [comment]
All our Oauth Tokens are revoked as well.

**Comment by Gareth064** [comment]
I was getting this returned starting last night `oauth_problem=token_revoked` from two personal etsy shops (I am using personal apps as well)

At first I assumed it was because we reset our password of the etsy accounts, but then I realised that we reset the password of only 1 etsy account and not the other. But this issue was on both.

We are still using v2 API and OAuth1 with these personal apps.

To resolve it, I had to generate new private tokens\secrets from both shops and now its working again.

**Comment by main24** [comment]
Problem still exists for us, dropped an email, no response so far.

**Comment by nateswart** [comment]
I will be following up internally on the additional issues being mentioned here and will post back updates.

**Comment by nateswart** [comment]
API keys were in fact restored last night, however user tokens for v2 endpoints may still be experiencing issues. Obtaining new tokens is working for some users, but we are still working on a more scaleable solution for all users.

Re-opening this ticket to help track and provide comms as this issue progresses.

**Comment by stickfigure** [comment]
Confirming that we still have a lot of invalid tokens. Spot-checking, the v2 tokens seem to be invalid and the v3 tokens seem to be working (we upgrade when users reconnect, though we haven't forced everyone yet). We'd rather not send out surprise emails forcing everyone to reconnect in a hurry and would definitely like to get the v2 tokens back. Thanks.

**Comment by swisst182** [comment]
Any news on this issue, the internal in-house application and Royal Mail applications have not been able to reconnect since yesterday over 24hr ago!

**Comment by pokusman** [comment]
me too :-(

**Comment by Byteschmiede** [comment]
+1 Same issues here

**Comment by ablagoev** [comment]
+1

Refreshing the oauth token worked in one of the applications I am managing, but did not fix the issue for the other one.

**Comment by hemaldev** [comment]
> Any news on this issue, the internal in-house application and Royal Mail applications have not been able to reconnect since yesterday over 24hr ago! This is using the v2

+1

**Comment by Gareth064** [comment]
To get royal mail to work again I had to delete and recreate it.... unfortunately this meant royal mail imported all our orders again duplicating loads of data 😭 so I would only do that as a last resort

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by swisst182** [comment]
Not an option when we have thousands of orders!

**Comment by benjymouse** [comment]
hey @etsyachristensen any update this morning? thanks

**Comment by codyschneiderx** [comment]
@etsyachristensen where are we at with this? Got an email back finally from developers@etsy.com and all that was said is that all responses from here out will be automated lol 

Screenshot - https://www.loom.com/i/4b1f0198462342519d940b6e5b95cfa0

**Comment by nateswart** [comment]
We believe we have the final fix for the lingering access issues about ready to go. I hope to post a more official update here shortly.

**Comment by nateswart** [comment]
The team is still working on implementing the fix for this issue. Once I have more information, I’ll continue to update this thread.

**Comment by nige123** [comment]
Our internal order processing application started failing two days ago. The v2 API calls now receive a "token_revoked" response. This is an internal application that has worked consistently for years - the operations team are now under pressure to manually process incoming orders and dispatch labels. This is costing the business time, money, stress and customer goodwill!

Revisiting the **dire** Etsy oauth docs is giving me nightmares too. 

For an internal shop app like this one a simple shop-held secret is all that is required - to BOTH authenticate and authorise API access. Forcing in house apps to jump through all the oauth hoops is bonkers. A simple API access key (revokable by the shop owner) is simpler and more secure.

I hope this bug is resolved as soon as possible. 

In the longer term I hope the API team can implement a sane and simple access key solution for in-house applications?!

**Comment by swisst182** [comment]
Just for anyone like me who has had this issue because of v2 Api dependencies, they are planning to shut down the v2 access end of the year.

I wasn't aware of this, but hey, the more you know I guess.

From the esty API v3 website 

`Launch stages#
These stages in advance of the general release of Open API v3 and the sunset of v2 are meant to give you ample time to migrate, test, ask questions and give feedback about our new API.

Q4 2021 Q1 2022 Q3/Q4 2022
v2 will remain active. v2 may not receive all new feature upgrades. All newly created apps must use v3. Access to v2 endpoints are removed and v2 is officially sunset.
v3 will continue to get fixes and updates.  Existing v2 apps can continue using v2. v2 endpoint calls will fail`

**Comment by Gareth064** [comment]
> Our internal order processing application started failing two days ago. The v2 API calls now receive a "token_revoked" response. This is an internal application that has worked consistently for years - the operations team are now under pressure to manually process incoming orders and dispatch labels. This is costing the business time, money, stress and customer goodwill!
> 
> Revisiting the **dire** Etsy oauth docs is giving me nightmares too.
> 
> For an internal shop app like this one a simple shop-held secret is all that is required - to BOTH authenticate and authorise API access. Forcing in house apps to jump through all the oauth hoops is bonkers. A simple API access key (revokable by the shop owner) is simpler and more secure.
> 
> I hope this bug is resolved as soon as possible.
> 
> In the longer term I hope the API team can implement a sane and simple access key solution for in-house applications?!

Shopify uses OAuth2.0 as well, but like you are saying, if It's just a personal App then a one-time client/secret pair of codes is all that is needed. But once you want a public app then you have to do the token refresh juggle.

**Comment by huppy** [comment]
> The team is still working on implementing the fix for this issue. Once I have more information, I’ll continue to update this thread.

Any update yet please?

**Comment by nateswart** [comment]
Late last night our final cleanup script began processing. Throughout the night we have seen a steady decline in the errors and are now holding steady at pre-incident levels. We will continue to monitor the situation over the course of today but are considering the issue largely resolved now.

As someone noted above, v2 applications should be moving to v3 as soon as possible. This issue primarily affected API v2, but is unrelated to the sunset. That said, We have extended the v2 retirement deadline a number of times but will soon be making an updated announcement confirming a final sunset for v2. 

Please consider updating your applications as soon as possible to avoid additional service disruptions.

**Comment by rkistaps** [comment]
Hi, @nateswart and @etsyachristensen. We are seeing auth issues all over again for both v2 and v3. We cannot sync any store at the moment
