### ISSUE TITLE
[BUG]: Duplicate Shop Names returned through V3 API

### ISSUE THREAD

**Issue by mahesh352** [etsy/open-api#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

When we request a shop name we are getting 4 results instead of one in V3 APIs. But it is working as expected in V2.

V3 API:
https://openapi.etsy.com/v3/application/shops?shop_name=WhimsicalGeek
Response : Count=4 
Shop names returned: WhimsicalGeek, GeekItUpCreations, WhimsicalGeekerySoap, TheWhimsicalGeek
V3 API is returning partial match shops instead of an exact match.

V2 API:
https://openapi.etsy.com/v2/shops/WhimsicalGeek?api_key=xxxxxxx
Response : Count=1 
Shop names returned: WhimsicalGeek

Could you please let us know how to handle the above issue? Is this expected or due to some bug on V3 API?

Thanks,
Mahesh

### Steps to reproduce

V3 API to run in Postman :
https://openapi.etsy.com/v3/application/shops?shop_name=WhimsicalGeek

V2 API to run in Postman :
https://openapi.etsy.com/v2/shops/WhimsicalGeek?api_key=xxxxxxx

### Expected behavior

V3 API shall return one shop_name with exact match.

**Comment by penalty-zone** [comment]
Hey bro I think you are using SearchShops, why not just use FindShops. SearchShops is originally a fuzzy match

**Comment by etsyachristensen** [comment]
@mahesh352 The endpoint you are using is the correct endpoint. The results you are getting are correct in OpenAPI V3. The reason being is the expanded nature of the find endpoint. The search engine in our system is seeing the "whimsicalgeek" string in 3 of those shop names so they come back as a positive match. The 4th has Geek in the shop name and Whimsical is in the username for that shop.

This is intentional behavior.
