### ISSUE TITLE
getListingFile should return a download link for the file

### ISSUE THREAD

**Issue by neilnguyendev** [etsy/open-api#602]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/files/{listing_file_id}

### Proposed Endpoint Design Change

Should return a download link for the file.

### Why are you proposing this change?

I can't figure out a way to get my listing file by API v3.

**Comment by etsyachristensen** [comment]
@neilnguyendev This is by design. If listing files were available to download via a URL you could fetch from the API, they would not be protected and locked to a sale. Each URL for downloading is unique to the purchase and tracked to ensure that buyers are getting the files they have paid for and no one else.
