### ISSUE TITLE
[DOCS]: Where did the "Required" nodes go on Schemas?

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

 https://www.etsy.com/openapi/generated/oas/3.0.0.json

### What would you like to change?

I was going to update my .NET wrapper library and do to this I would compare the AOS contents against the last time I did an update.

I have noticed that on ALL schemas, the required node has now been removed. I felt this would have been useful for code generators when generating models and applying the required annotation on each property (I'm using C#)

Have they been removed because the "required" logic is complicated and mostly scenario based?

![image](https://user-images.githubusercontent.com/22307223/194750261-4a244994-9199-419d-a70a-cd28922a10e3.png)

**Comment by etsyachristensen** [comment]
@Gareth064 We removed the required because it is in fact very scenario based. For instance, doing a getListing endpoint only requires the listing_id. But the RETURNED object was "requiring" all of the fields on return. It made the documentation confusing because having a field "required" suggests an input. The response data set is the data set. All of those fields will always be there, whether they have a value, are null or empty.
