### ISSUE TITLE
Add SKU to the createdraftlisting endpoint

### ISSUE THREAD

**Issue by iandante77** [etsy/open-api#656]
There is no way to add an SKU to the request body when listing products using the createDraftListing endpoint.
The reason I say the SKU should be part of the body is that there is no other primary denominator that will help match to products when listing the properties and attributes after getting the listingids. If this were possible, it would make life a lot easier. The API's purpose is to make listing easier.

**Comment by etsyachristensen** [comment]
@iandante77 Back in June we made a change to the create listing endpoint that would direct users to begin using the [updateListingInventory](https://developers.etsy.com/documentation/reference#operation/updateListingInventory) endpoint in order to update data around product specific listings. This includes price, quantity and SKU. Please checkout that endpoint as you can define the SKU there. Even listings that have no variations use the updateListingInventory endpoint to update that data.
