### ISSUE TITLE
[ENDPOINT] Proposed design change for <getListing> 

### ISSUE THREAD

**Issue by ulandj** [etsy/open-api#96]
**Current Endpoint Design**
What in the current endpoint design do you think is missing or find confusing?

With V2 API it is possible to fetch listings along with necessary data like ['Images', 'Inventory', 'Attributes'] (as associations) with a single request. But with V3 API we will need to do multiple requests to get the necessary data for a listing. In addition, the new V3 [getListing](https://www.etsy.com/openapi/developers#operation/getListing) endpoint doesn't allow to fetch multiple listings passing remote ids like `getListing` endpoint in V2 API.

**Proposed Endpoint Design Change**
Make it possible to fetch all the necessary data(['Images', 'Inventory', 'Attributes'] ) of multiple listings by remote ids with a single request in `getListing` V3 endpoint.

**Why are you proposing this change?**
Currently, we pull listings using the [getListing](https://www.etsy.com/developers/documentation/reference/listing#method_getlisting) V2 endpoint passing several remote listing ids and [Images Inventory Attributes] associations. Thus we pull all necessary data with a single request:
```
Etsy::Listing.find([array of listing ids], { includes: ['Images', 'Inventory', 'Attributes'] })
```

So, in order to achieve the above results in the V3 API we will have to do many API requests:
```
listing_ids.each do |listing_id|
  remote_listing = getListing(listing_id: listing_id)
 remote_listing['Images'] = getListingImages(shop_id: 'shopid', listing_id: listing_id)
 remote_listing['Inventory'] = getListingInventory(listing_id: listing_id)
 remote_listing['Attributes'] = getListingProperties(listing_id: listing_id)
end
```

As a result, we must do 4 separate requests to fetch the necessary data for one listing. if we have 100 listing ids then we must do 100 * 4 = 400 requests. 
To fetch 100 listings with all required data:
V2 API = 1 request
V3 API = 400 requests

I hoped that the API is optimized and make developers life easier but as we see it is not. 

Is there a chance to consider optimizing fetching listings by remote ids? 
Thanks

**Comment by harjas** [comment]
Thanks @ulandj! Thank you such a detailed description to help us understand your problem. We hear you on how this can be difficult. We've made a note of this and will update you as and when we work on a fix.

**Comment by benjymouse** [comment]
This would be great for us too. Without support for Associations our app will be much slower and we'd be hitting that 10k API request / day. Here's hoping there is good news soon!

**Comment by capndesign** [comment]
We’re still working on a solution to support associations, but it would be helpful to hear which ones are critical for your applications. In the meantime, 👀 https://www.etsy.com/openapi/developers#operation/getListingsByListingIds

**Comment by benjymouse** [comment]
Hey @capndesign - that's great to hear. I LOVE the getListingsByListingIds - we will check that out!

Here are some of the associations we use frequently:

/listings: MainImage, Images, Attributes, ShippingInfo
/transactions: MainImage, Listing
/users: Shops,Profile

**Comment by sampok** [comment]
/listings:
- Images(url_570xN,url_fullxfull,full_width,full_height)
- Shop(shop_name)
- ShippingInfo(origin_country_id)

**Comment by mattkingshott** [comment]
/listings/[active, expired]

* MainImage(url_170x135)
* Images(listing_image_id,listing_id,rank,url_fullxfull,url_75x75)
* Section(shop_section_id,title)

/shops/[id] AND /users/[id]/shops

* User/Profile(image_url_75x75)

/shops/[id]/transactions

* Receipt
* Listing/MainImage
* Listing/Images
* Listing/Section

In addition, the inability to use `?page=x` is making things very difficult for us

**Comment by x-bass** [comment]
It would be great if you can keep and support in v3:

**/listings/active**
- MainImage (url_100x100)
- sort_on=score
- geo_level=country

**/shops/[shop_name]/listings/active**
- MainImage (url_100x100),
- ShippingInfo (origin_country_id)
- sort_on=created

**/users/[user_id]**
- Shops (shop_id, shop_name, creation_tsz, listing_active_count)
- Profile (transaction_sold_count, country_id)

**/listings/[listing_id]**
- MainImage (url_170x135)

**/listings/[listing_id]/transactions**
- views
- tags
- MainImage (url_170x135)

**Comment by benjymouse** [comment]
+1 for sort on score

**Comment by main24** [comment]
> We’re still working on a solution to support associations, but it would be helpful to hear which ones are critical for your applications. In the meantime,  https://www.etsy.com/openapi/developers#operation/getListingsByListingIds

@capndesign thank you for the tip, however unfortunately that does not solve the issue as we still have to make several additional requests per **each** product for images, inventory, etc, which can easily consume all the daily quota.

Yet another improvement for listings would be an ability to request listings modified/created since some date. And sort them accordingly.

**/shops/{shop_id}/receipts/{receipt_id}**
We noticed changes in the receipts endpoint: now it does not return **buyer_email**, which means now it's required to make an additional request just for email per each order which will affect requests quota as well. Would be really handy to have this attribute right in the receipt response along with shipping address.

Thank you in advance.

**Comment by mattkingshott** [comment]
> > We’re still working on a solution to support associations, but it would be helpful to hear which ones are critical for your applications. In the meantime,  https://www.etsy.com/openapi/developers#operation/getListingsByListingIds
> 
> @capndesign thank you for the tip, however unfortunately that does not solve the issue as we still have to make several additional requests per **each** product for images, inventory, etc, which can easily consume all the daily quota.
> 
> Yet another improvement for listings would be an ability to request listings modified/created since some date. And sort them accordingly.
> 
> **/shops/{shop_id}/receipts/{receipt_id}**
> We noticed changes in the receipts endpoint: now it does not return **buyer_email**, which means now it's required to make an additional request just for email per each order which will affect requests quota as well. Would be really handy to have this attribute right in the receipt response along with shipping address.
> 
> Thank you in advance.

Absolutely this. I would also like to limit transactions to a recent period. 

Associations across the board are critical!

**Comment by DemiImp** [comment]
Is the inclusion of images/associations going to be included for all listing requests?  The most common API request we do is findAllListingsActive with one of the primary goals being accessing the images.  Like other people have noted, not being able to immediately access the images making using the v3 API significantly less efficient.  Customers with really large shops would be the most affected by this.

**Comment by harjas** [comment]
Hello everyone! Based on the discussions in this thread (and looking at usage of associations in v2), we've added support for associations in the getListing and getListingInventory endpoints. You can refer to the release notes and our reference doc [here](https://developers.etsy.com/documentation/reference/#operation/getListing.) for more info. This is not to say that these are the _only_ associations we will support but for now we've tried to accommodate the most used associations for the most used endpoints

**Comment by mattkingshott** [comment]
@harjas this is a good start, but my application depends on the association support I've outlined in [here](#issuecomment-862397481). In addition, as others have clearly outlined in this thread, many more associations are needed to keep these applications functioning.

When will we receive an update on additional association support?

**Comment by main24** [comment]
@harjas thank you for that! Though looking forward for more updates as current design still requires to make the same number of requests for complete listings data, basically unfortunately it doesn't cover the original issue described in the thread starter.

**Comment by DemiImp** [comment]
@harjas - So if I wanted to get all active listings of a shop with their images, I would first use findAllActiveListingsByShop and take all 100 listing IDs and then add them to the query getListingsByListingIds using the includes="images" parameter?

**Comment by etsyachristensen** [comment]
@DemiImp - Your process is exactly right for the moment. We can look at adding the associations to the `findAllActiveListingsByShop` endpoint as well, hopefully soon.

**Comment by VasilVelikov** [comment]
+1 vote for the following associations:

/listings: MainImage, Images, Shop, ShippingInfo
/shops: User
/user: Profile

My application relies heavily on them.

**Comment by chris-rogala** [comment]
@etsyachristensen @harjas If associations are not going to be included in V3 as they were in V2, would Etsy be willing to up the daily limits to say 30K instead of 10K? I know that seems high, but in all honesty, the new design is going to add a lot more unnecessary traffic to the API.

Looking at just the images association in listings, we can see how much this will impact this microservice. For example, we have over 300 items in our shop. Currently, a developer can make 4 calls to get the listings and their images. With the current design, the code has to make over 300 calls. Going from 4 calls to 300, while keeping the limits the same is not really that fair.

I know from a RESTful services perspective, the ideas is to have sub resources, but having designed and led the development of quote a few RESTful services in my career, which span multiple departments in an enterprise, I do know the architects must balance RESTful concepts with being practical for the end users.

Lets look at the images and listings, and assume these are microservices. I would assume the images are a separate microservice in your architecture, but some of the properties of an image (paths) should be stored with the listing resource. With microservices, it is okay to duplicate the data across multiple microservices. It's actually widely recommended to do this to reduce the chatter between microservice and increase performance.

If the concern is keeping the resources in sync, then you could have the listings microservice subscribe to a change feed within the images microservice. By setting up these events and allowing the microservices to subscribe to them, they can pop messages off the feed and update themselves appropriately.

That being said, I do highly recommend either adding the support to all the above associations or increasing the daily limits significantly until the associations are created. I also recommend doing some analysis on V2 usage data to get a better grasp of how much these associations are being utilized and the impact of not having them will have on the developers, especially before the v2 API is deprecated.

**Comment by etsyachristensen** [comment]
@chris-rogala We actually added the associations for images, shop and user to the listings endpoints.

See the documentation here: https://developers.etsy.com/documentation/reference#operation/getListing

If you pass in "includes" as an input parameter with a comma delimited list of "Images", "Shop" or "User". Adding the associations does additionally not take away from your rate limit.

**Comment by chris-rogala** [comment]
@etsyachristensen I know it was added to the listings endpoint, but my point is still valid. In v2, I could call `/v2/listings/active?includes=Images` and it would return all the images with the collection of listings. With 300+ listings, I previous only had to make 4 calls to get images and listing properties. Now, I have to make 4 calls and then 300+ calls since the association is at the listing resource and not the collection of listings.

**Comment by etsyachristensen** [comment]
Ah I see what you are saying. Sorry for the misunderstanding. We did add the associations also to the `getListingsByListingIds` so if you know your listing ids, you can get that information. So you could first do the `findAllListingsActive` or `findAllActiveListingsByShop` endpoints to get the listing ids. Then you can do `getListingsByListingIds` with the "Images" include. I know it's not the most ideal solution, but it's what we have for now. And I do also realize there are other associations we haven't provided yet. Whether we will add those or not is still to be determined.

**Comment by chris-rogala** [comment]
@etsyachristensen Thanks for sharing that. That does help but it makes the API a little harder to understand. Is there going to be support added for the `field` query parameter ([https://www.etsy.com/developers/documentation/getting_started/resources#section_fields](https://www.etsy.com/developers/documentation/getting_started/resources#section_fields))? That's a lot of data to pull twice. It would be nice to query for just the ids of the listings and then call the `getListingsByListingIds` endpoint.

**Comment by chris-rogala** [comment]
@etsyachristensen This is another example of why the rate limits may need to be increased. The ship-by-date and estimated delivery date is not available in v3 [https://github.com/etsy/open-api/issues/211](https://github.com/etsy/open-api/issues/211). For now, I am going to have to hit both v2 and v3 just to get these properties.

**Comment by chris-rogala** [comment]
@etsyachristensen @harjas While support was added to the [getListingInventory](https://developers.etsy.com/documentation/reference#operation/getListingInventory) endpoint to include `Listing`, the `Inventory` association was not added to the [getListingsByListingIds](https://developers.etsy.com/documentation/reference#operation/getListingsByListingIds) endpoint. This was an association that was originally requested by the original poster in May.

Right now, it looks like we will have to enumerate through each individual listing to get the **ShopListing Inventory** since there isn't a batch endpoint in inventory like there is in the **ShopListing** resource. For just one shop, we have over 300 listings, so not only will it take up 300 of our daily requests, we will also have to pay for the processing time of each of those requests. I am very concerned since Etsy has stated they will be ending support of v2 by the end of 2021 and I doubt these associations will make it before v2 is deprecated.

**Comment by etsyachristensen** [comment]
@chris-rogala Sunset of V2 has been pushed out to 2022. I'm not sure the exact timeline on that. I'm not sure there even is an exact timeline. I just know it has been pushed.

That said, your request is certainly valid. I'll add it the growing list of endpoint changes.

**Comment by etsyachristensen** [comment]
Also, I will note that the associations that we did add previously (Images, Shop and User) were based on our analytics. Most of the decisions about what to support immediately, what to deprecate and what to support in time came from analysis of the V2 endpoint usage. These were not simple hand-wave decisions. We would love to have a 1:1 parity with V2, but a large part of this V3 rebuild was to introduce greater stability, better security and allow for future development over the long run versus having to rebuild again in a few years. When we look at adding associations, we have to consider a great many factors in how the internal architecture handles pulling those things in and making sure that changing one endpoint doesn't affect many other endpoints, or if it does, then accounting for those in the other endpoints. Please know that we are actively pursuing many of these requests.

**Comment by mattkingshott** [comment]
@etsyachristensen that's good to hear. As several have said, the loss of these associations will cause difficulty, so fingers crossed that most of the requests will end up in v3.

**Comment by chris-rogala** [comment]
@etsyachristensen I completely understand prioritizing the work based on usage. However, it is very concerning when the dev community is given 6 months to switch to a brand new platform that isn't remotely close to the previous version, complete testing and also have this completed during the busiest season of the year. I'm referencing this particular post: https://github.com/etsy/open-api/issues/149

Also, while completing the analysis, I do recommend surveying the dev community to see what they have slated for development. I'm not sure about other devs, but we have been holding off on certain projects because of multiple reason. One of which was the development of v3 and the unknown associated with that. For us, our shop has been impacted by the pandemic, and projects we were hoping to work on last year were put on the back burner because we did not have the labor for other activities.

I am looking forward to a strong relationship between Etsy and the dev community and I don't know about others, but I am very happy to have a github repo to provide feedback. I've also been involved in multiple projects associated with rearchitecting systems, so I do know the issues around making that shift. Any transparency that Etsy can provide would be greatly appreciated.

**Comment by Hytgarh** [comment]
If the options get implemented, may i suggest to also have option for including variation-iamges

**Comment by DemiImp** [comment]
Can someone explain how to use include=Images?

I am in the middle of migrating from v2 to v3 and it didn't work.  I got all of the listing data for each of the listings I listed in my URL, but no images.

My URL looks like: listings/batch?listing_ids=76.....86&includes=Images

**Comment by main24** [comment]
Hi @etsyachristensen,

Is there any chance that `Inventory` association will be added to the listings endpoints? Inventory data is used to build product variants and track available quantity, which means with V3 it's required to fetch inventory per product individually once it gets updated -- that will be quite expensive in terms of requests quota usage. So adding inventory association to listings index endpoints would be really appreciated.

Thank you in advance.

**Comment by etsyachristensen** [comment]
@main24 At this point there are no plans to add that association. That's not to say it won't happen, just that we haven't discussed it or made any decisions.

**Comment by main24** [comment]
@etsyachristensen Thanks for the reply. Just to add a bit more votes for `Inventory` association https://github.com/etsy/open-api/issues/236

**Comment by marie-erank** [comment]
hi @etsyachristensen , can I ask if adding back the `view` property is being considered for this endpoint?
